### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by 1581052236** [shadowsocks/shadowsocks-manager#103]
我在webgui.yml文件中填写了正确的邮箱，密码以及smtp服务器，注册的时候发送验证码，一直在发送，xshell窗口提示以下错误：
[2017-03-01 21:11:07.194] [ERROR] system - { Error: connect ETIMEDOUT 1.1.1.1:4001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '1.1.1.1',
  port: 4001 }
[2017-03-01 21:11:07.197] [ERROR] system - Unhandled Rejection at: Promise Promise { <rejected> 'failure' } reason: failure

这个是什么原因？

**Comment by 1581052236** [comment]
而且重置密码也被链接到了https://wall.gyteng.com这个网站

**Comment by gyteng** [comment]
这个`1.1.1.1`是示例的服务器地址，你要换成你服务器实际的地址才行

**Comment by 1581052236** [comment]
这个1.1.1.1在哪个文件中？我修改了 /root/.ssmgr/webgui.yml文件里的1.1.1.1为自己的服务器ip，同样出现这个问题

**Comment by 1581052236** [comment]
webgui.yml文件内容：

type: m
empty: false

manager:
  #自己的服务器ip
  address: 180.76.151.137:4001
  password: '123456'
  # 这部分的端口和密码需要跟上一步 manager 参数里的保持一致
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
  email:
    use: true
    username: 'JudyTAube@hotmail.com'
    password: '邮箱密码'
    host: 'smtp-mail.outlook.com'
    # 这部分的邮箱和密码是用于发送注册验证邮件，重置密码邮件使用的
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://aa.pandaoc.xyz/'
  alipay:
    use: true
    appid: 2015012108272442
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'

**Comment by gyteng** [comment]
删除`~/.ssmgr/webgui.sqlite`文件并重新运行

**Comment by 1581052236** [comment]
好的，谢谢你

**Comment by 1581052236** [comment]
我删除了ss.sqlite和webgui.sqlite文件，然后重新打开xshell，并执行命令，注册的时候，发送验证码一直在转圈，在[root@instance-jwu8kydr ~]# **ssmgr -c ss.yml**命令窗口，一直出现以下信息（<Buffer 00 14>）：
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-01 21:28:30.360] [INFO] system - System start.
[2017-03-01 21:28:30.639] [INFO] system - Config file path:  /root/.ssmgr/ss.yml
20
<Buffer 00 14>
20
<Buffer 00 14>
20
<Buffer 00 14>
20
<Buffer 00 14>
20
<Buffer 00 14>
20
<Buffer 00 14>
20
<Buffer 00 14>
20
<Buffer 00 14>
20
<Buffer 00 14>

**Comment by 1581052236** [comment]
现在，在[root@instance-jwu8kydr ~]# ssmgr -c webgui.yml命令窗口，出现以下错误：
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-01 21:28:40.112] [INFO] system - System start.
[2017-03-01 21:28:40.386] [INFO] system - Config file path:  /root/.ssmgr/webgui.yml
[2017-03-01 21:28:41.656] [INFO] webgui - server start at 0.0.0.0:80
[2017-03-01 21:30:52.101] [ERROR] email - Send code fail: Error: Connection timeout
[2017-03-01 21:30:52.107] [ERROR] webgui - { Error: Connection timeout
    at SMTPConnection._formatError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._onError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:514:16)
    at SMTPConnection.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:236:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', command: 'CONN' }
[2017-03-01 21:32:52.049] [ERROR] email - Send code fail: Error: Connection timeout
[2017-03-01 21:32:52.051] [ERROR] webgui - { Error: Connection timeout
    at SMTPConnection._formatError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._onError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:514:16)
    at SMTPConnection.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:236:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', command: 'CONN' }


提示链接超时，我使用的是微软邮箱

**Comment by gyteng** [comment]
这个错误是邮件发不出去，请看看你的邮箱设置里有没有开启stmp协议之类的东西。

**Comment by 1581052236** [comment]
我在微软邮箱里开启了pop设置，没有开启smtp设置的地方，我换其他的邮箱试试，谢谢你

**Comment by vinsec** [comment]
迷之bug 一直得不到解决

**Comment by sealionking** [comment]
是否因为webgui默认的smtp端口是465啊。我的mail server是25端口啊

**Comment by drshiki** [comment]
> 
> 
> 是否因为webgui默认的smtp端口是465啊。我的mail server是25端口啊

可以设置port参数，我看log里面是有效的，虽然官方文件没写出来。不过我后来还是用了163的，默认465，直接就可以用了

**Comment by drshiki** [comment]
> 
> 
> 现在，在[root@instance-jwu8kydr ~]# ssmgr -c webgui.yml命令窗口，出现以下错误：
> /usr/lib/node_modules/shadowsocks-manager/lib/
> [2017-03-01 21:28:40.112] [INFO] system - System start.
> [2017-03-01 21:28:40.386] [INFO] system - Config file path: /root/.ssmgr/webgui.yml
> [2017-03-01 21:28:41.656] [INFO] webgui - server start at 0.0.0.0:80
> [2017-03-01 21:30:52.101] [ERROR] email - Send code fail: Error: Connection timeout
> [2017-03-01 21:30:52.107] [ERROR] webgui - { Error: Connection timeout
> at SMTPConnection._formatError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:528:15)
> at SMTPConnection._onError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:514:16)
> at SMTPConnection. (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:236:14)
> at ontimeout (timers.js:365:14)
> at tryOnTimeout (timers.js:237:5)
> at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', command: 'CONN' }
> [2017-03-01 21:32:52.049] [ERROR] email - Send code fail: Error: Connection timeout
> [2017-03-01 21:32:52.051] [ERROR] webgui - { Error: Connection timeout
> at SMTPConnection._formatError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:528:15)
> at SMTPConnection._onError (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:514:16)
> at SMTPConnection. (/usr/lib/node_modules/shadowsocks-manager/node_modules/.2.12.0@smtp-connection/lib/smtp-connection.js:236:14)
> at ontimeout (timers.js:365:14)
> at tryOnTimeout (timers.js:237:5)
> at Timer.listOnTimeout (timers.js:207:5) code: 'ETIMEDOUT', command: 'CONN' }
> 
> 提示链接超时，我使用的是微软邮箱

你试试配置port参数，outlook的smtp端口是587，node那个邮件插件默认用的465的
