### ISSUE TITLE
need some help !

### ISSUE THREAD

**Issue by buffgeter** [shadowsocks/shadowsocks-manager#112]
[2017-03-07 13:59:50.263] [INFO] system - System start.
[2017-03-07 13:59:50.518] [ERROR] system - Caught exception: TypeError: Cannot read property 'split' of undefined

**Comment by gyteng** [comment]
Please parse the full error message,
and your node version, system verison.

**Comment by buffgeter** [comment]
root@vmi106909:~/.ssmgr# node -v
v6.10.0
ubantu 14,04
this is the only error

**Comment by gyteng** [comment]
and the ssmgr version?
user ssmgr -V to show the version

2017-03-07 21:25 GMT+08:00 buffgeter <notifications@github.com>:

**Comment by buffgeter** [comment]
root@vmi106909:~/.ssmgr# ssmgr -V
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-03-07 14:28:54.002] [INFO] system - System start.
shadowsocks-manager 0.5.12
root@vmi106909:~/.ssmgr#

**Comment by buffgeter** [comment]
[2017-03-07 14:28:54.002] [INFO] system - System start.
shadowsocks-manager 0.5.12

**Comment by gyteng** [comment]
maybe your config file was wrong

**Comment by buffgeter** [comment]
thank for your help . i'll check the config .

**Comment by gyteng** [comment]
check the ~/.ssmgr/default.yml, did you modify it before?

2017-03-07 21:40 GMT+08:00 buffgeter <notifications@github.com>:

**Comment by buffgeter** [comment]
no .

**Comment by buffgeter** [comment]
it work depend on this config file?

**Comment by gyteng** [comment]
yes, if you use ssmgr without -c, it will use ~/.ssmgr/default

2017-03-07 21:43 GMT+08:00 buffgeter <notifications@github.com>:

**Comment by buffgeter** [comment]
but i do used ssmgr with -c config file .

**Comment by buffgeter** [comment]
but i just use wiki ss.yml and webgui,yml .is there some 
error

**Comment by gyteng** [comment]
parse your config file here

2017-03-07 21:58 GMT+08:00 buffgeter <notifications@github.com>:

**Comment by buffgeter** [comment]
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:4000
manager:
  address: 127.0.0.1:4001
  password: 'free'
db: 'ss.sqlite'

**Comment by buffgeter** [comment]
type: m
empty: false

manager:
  address: my ip adr : 4001
  password: 'free'
  # 这部分的端口和密码需要跟上一步 manager 参数里的保持一致
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
      season:
        price: 30
        flow: 200000000000
      year:
        price: 120
        flow: 200000000000
  email:
    use: true
    username: '***'
    password: '***'
    host: 'smtp.gmail.com'
    # 这部分的邮箱和密码是用于发送注册验证邮件重置密码邮件使用的
  webgui:
    use: true
    host: '127.0.0.1'
    port: '80'
    site: 'http:/w**********'
    gcmSenderId: '24*****2'
    gcmAPIKey: '**********Y'
 
db: 'webgui.sqlite'

**Comment by gyteng** [comment]
Sorry, I have no idea about this error,
maybe you can use `--debug` to show the full logs

**Comment by buffgeter** [comment]
Anyway thank for your help.

**Comment by buffgeter** [comment]
[2017-03-07 15:09:06.367] [INFO] system - System start.
[2017-03-07 15:09:06.577] [INFO] system - Config file path:  /root/.ssmgr/webgui.yml
[2017-03-07 15:09:06.585] [INFO] system - { YAMLException: incomplete explicit mapping pair; a key node is missed at line 5, column 28:
      address: 178.238.226.112 : 4001
                               ^
    at generateError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:999:9)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockMapping (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at load (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at Object.safeLoad (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1584:10)
  name: 'YAMLException',
  reason: 'incomplete explicit mapping pair; a key node is missed',
  mark:
   Mark {
     name: null,
     buffer: 'type: m\*********************************  
     position: 58,
     line: 4,
     column: 27 },
  message: 'incomplete explicit mapping pair; a key node is missed at line 5, column 28:\n      address: 178.238.226.112 : 4001\n                               ^' }
[2017-03-07 15:09:06.597] [ERROR] system - Caught exception: TypeError: Cannot read property 'split' of undefined

**Comment by buffgeter** [comment]
[2017-03-07 15:09:06.367] [INFO] system - System start.
[2017-03-07 15:09:06.577] [INFO] system - Config file path:  /root/.ssmgr/webgui.yml
[2017-03-07 15:09:06.585] [INFO] system - { YAMLException: incomplete explicit mapping pair; a key node is missed at line 5, column 28:
      address: ****** : 4001
                               ^
    at generateError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:999:9)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readBlockMapping (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at load (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at Object.safeLoad (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1584:10)
  name: 'YAMLException',
  reason: 'incomplete explicit mapping pair; a key node is missed',
  mark:
   Mark {
     name: null,
     buffer: 'type: m\*********************************  
     position: 58,
     line: 4,
     column: 27 },
  message: 'incomplete explicit mapping pair; a key node is missed at line 5, column 28:\n      address: 178.238.226.112 : 4001\n                               ^' }
[2017-03-07 15:09:06.597] [ERROR] system - Caught exception: TypeError: Cannot read property 'split' of undefined

**Comment by gyteng** [comment]
Obviously something wrong in your config file

2017-03-07 22:16 GMT+08:00 buffgeter <notifications@github.com>:

**Comment by haodong** [comment]
I encountered the exact same error yesterday. Both either git repo and npm have the same problem. I tried on both ubuntu and debian.

**Comment by gyteng** [comment]
@haodong when you use `-c <filename>`, don't use the full path of the file, just put the file in `~/.ssmgr` and put the file name after `-c`, like `ssmgr -c default.yml`.
I will change the design of `-c` params later.

and the error of sqlite3, I have met the error messages and I don't know why. When you see it, just reinstall ssmgr to fix it, like:

```
sudo npm uninstall -g shadowsocks-manager
sudo npm install -g shadowsocks-manager
```

**Comment by haodong** [comment]
@gyteng Problem solved, thx!

**Comment by gyteng** [comment]
@haodong But I still don't know why sometimes sqlite module will not install in the project.

**Comment by haodong** [comment]
@gyteng Maybe because of its extra package required to download during installation.

I failed dozens of times yesterday until I set a proxy in my shell.
