### ISSUE TITLE
支付宝付款成功，数据不更新

### ISSUE THREAD

**Issue by KaiyangNi** [shadowsocks/shadowsocks-manager#120]
0.5.27

docker gyteng/ssmgr

支付宝订单失败

支付宝付款成后 显示成功 两分钟后更新 但数据并未更新 
后台查看付款信息是有的 但就是所付款的账号没有加时间

查看alipay log显示如下
[2017-03-13 14:28:28.060] [ERROR] alipay - 订单支付失败: [2017031*******361502] TypeError: Cannot read property 'flow' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:271:55)
    at next (native)
    at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:3:191)
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:3:437
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:3:99)
    at Object.setAccountLimit (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:336:18)
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:89:15
    at Array.forEach (native)
    at Timeout.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:72:10)
    at next (native)
    at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:253)
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:423

**Comment by gyteng** [comment]
0.5.29 已经修复此问题，稍后更新到docker上，多谢反馈问题
