### ISSUE TITLE
#120 问题依然存在 支付宝付款后不更新数据

### ISSUE THREAD

**Issue by KaiyangNi** [shadowsocks/shadowsocks-manager#122]
0.5.29

docker gyteng/ssmgr

 [ERROR] alipay - 订单支付失败: [2017031******8447845] TypeError: Cannot read property 'week' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:271:56)
    at next (native)
    at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:3:191)
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:3:437
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:3:99)
    at Object.setAccountLimit (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/account/index.js:336:18)
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:89:15
    at Array.forEach (native)
    at Timeout.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:72:10)
    at next (native)
    at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:253)
    at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:423

**Comment by gyteng** [comment]
请更新 0.5.32 解决

**Comment by KaiyangNi** [comment]
0.5.32 验证已经修复，感谢！
