### ISSUE TITLE
捕获异常

### ISSUE THREAD

**Issue by 1581052236** [shadowsocks/shadowsocks-manager#126]
shadowsocks-manager 0.5.33，centos 7系统

使用https://teddysun.com/486.html    一键安装脚本，安装了shadowsocks libev版

执行ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000 运行正常

在/root/.ssmgr/目录下新建了ss.yml文件，

执行ssmgr -c ss.yml的时候出现以下错误：
raven@1.1.4 alert: uncaughtException: 0152a09b48bd41dcad1d685e8d57ac59
[2017-03-16 09:29:24.726] [ERROR] system - Caught exception: TypeError: Path must be a string. Received undefined

**Comment by gyteng** [comment]
请贴出你的配置文件，另外运行的时候加上--debug可以显示更详细的错误信息

古宇腾 <igyteng@gmail.com>于2017年3月16日 周四17:49写道：

**Comment by 1581052236** [comment]
原来是手误，多了一个空格，执行ssmgr -c webgui.yml的时候出现了以下错误：
[2017-03-16 10:50:00.595] [ERROR] system - Error: The GCM API Key should be a non-empty string or null.
    at Object.WebPushLib.setGCMAPIKey (/usr/lib/node_modules/shadowsocks-manager/node_modules/web-push/src/web-push-lib.js:35:11)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/push.js:8:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/home.js:11:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/route.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/index.js:74:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at Promise.all.then (/usr/lib/node_modules/shadowsocks-manager/lib/init/loadPlugins.js:36:9)

**Comment by 1581052236** [comment]
ss.yml文件内容：
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:4000
manager:
  address: 0.0.0.0:4001
  password: '123456'
db: 'ss.sqlite'

**Comment by 1581052236** [comment]
webgui.yml文件内容：
type: m
empty: false

manager:
  address: 180.76.151.137:4001
  password: '123456'
  # 这部分的端口和密码需要跟上一步 manager 参数里的保持一致
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
  email:
    use: true
    username: 'xxx@163.com'
    password: 'xxx'
    host: 'smtp.163.com'
    # 这部分的邮箱和密码是用于发送注册验证邮件，重置密码邮件使用的
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
	#自己的域名
    site: 'http://xxx.com/'
  alipay:
    use: true
    appid: 2015012108272442
    notifyUrl: ''
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'

**Comment by gyteng** [comment]
配置文件里的参数gcmSenderId没有填写。这个是用于Chrome消息推送的，后面的版本我把它改成选填吧。

**Comment by 1581052236** [comment]
这个gcmSenderId是随便写，还是什么？

**Comment by gyteng** [comment]
不是随便填写，需要去firebase里申请一个账号做推送用的

**Comment by 1581052236** [comment]
好的，谢谢你，我去申请一个

**Comment by KmustXH** [comment]
登陆的时候一直提示网络异常请稍后再试怎么办， User[xh970307@163.com] login fail: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
