### ISSUE TITLE
v0.5.67 cannot run, please help

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#164]
### What version of shadowsocks-manager are you using?
0.5.67 (0.5.66 works well)

### What operating system are you using?
Ubuntu 16.04 LTS x64

### What version of Node.js are you using?
Node 6.10.1 LTS
npm 4.4.4

### What did you do?
npm i -g shadowsocks-manager

### What did you expect to see?
install & run without problem

### What did you see instead?
```
npm i -g shadowsocks-manager
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle shadowsocks-manager@0.5.67~prepublish: cannot run in wd %s %s (wd=%s) shadowsocks-manager@0.5.67 gulp /root/shadowsocks-manager
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/bin/ssmgr -> /usr/lib/node_modules/shadowsocks-manager/bin/ssmgr

> sqlite3@3.1.8 install /usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node" is installed via remote

> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/shadowsocks-manager/node_modules/spawn-sync
> node postinstall
/usr/lib
|...
|...

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/shadowsocks-manager/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
```
ssmgr -h
/usr/lib/node_modules/shadowsocks-manager/lib/
/usr/lib/node_modules/shadowsocks-manager/bin/ssmgr:7
process.chdir(lib);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/bin/ssmgr:7:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

```

**Comment by gyteng** [comment]
```
cd /usr/lib/node_modules/shadowsocks-manager
npm run build
```
and try again ssmgr

**Comment by cokebar** [comment]
thanks. it works
