### ISSUE TITLE
作者大大您好 按照教程安装了网站 但是启动server.js时出现了问题

### ISSUE THREAD

**Issue by magiclyu** [shadowsocks/shadowsocks-manager#17]
/home/shadowsocks-manager/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/shadowsocks-manager/node_modules/connect-mongo/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at exports.express (/home/shadowsocks-manager/server/app.js:104:22)
    at nextTask (/home/shadowsocks-manager/node_modules/async/dist/async.js:6627:18)
    at /home/shadowsocks-manager/node_modules/async/dist/async.js:6621:17

如下 请问这是哪里出错了吗？

**Comment by gyteng** [comment]
我估计是你的node版本太低
2016年6月21日 下午5:38，"magiclyu" <notifications@github.com>写道：

**Comment by magiclyu** [comment]
使用node -v查看版本是v0.10.43 应该是挺新的了吧
(>﹏<)

**Comment by gyteng** [comment]
需要node 4以上版本，0.10的不支持es6无法正常运行
2016年6月21日 17:57，"magiclyu" <notifications@github.com>写道：
