### ISSUE TITLE
have some issue when I went to modified server information

### ISSUE THREAD

**Issue by jiashooter** [shadowsocks/shadowsocks-manager#170]
Environment base on Centos7 and Nodejs 6.10.2

[2017-04-02 07:29:42.517] [INFO] system - System start.
raven@1.2.0 alert: failed to send exception to sentry: HTTP Error (429): Creation of this event was denied due to rate limiting
[2017-04-02 07:30:38.519] [ERROR] system - { Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:572:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Error: connect to ssmgr[s] fail
    at Socket.client.on.err (/usr/local/lib/node_modules/shadowsocks-manager/lib/services/manager.js:102:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[2017-04-02 07:30:38.531] [ERROR] express - [undefined] PUT 403 22ms /api/admin/server/1

Thank you.

**Comment by gyteng** [comment]
Because the server information is incorrect, when you modified server info, it will try to connect the server.

**Comment by pright** [comment]
建议在修改或者添加服务器信息时，由于服务器配置错误连接不上时弹出一个提示说明，现在没有提示的情况下有时会觉得是因为网络卡之类原因导致没有修改或者添加成功。

**Comment by gyteng** [comment]
@pright 已修复
