### ISSUE TITLE
尝试在centos安装后运行出现以下错误信息

### ISSUE THREAD

**Issue by XOXoNone** [shadowsocks/shadowsocks-manager#18]
`# node server.js
[2016-06-22 01:35:06.741] [INFO] server - 开始加载数据库配置文件
[2016-06-22 01:35:06.758] [INFO] server - 加载数据库 history.js
[2016-06-22 01:35:06.760] [INFO] server - 加载数据库 oneSecond.js
[2016-06-22 01:35:06.763] [INFO] server - 加载数据库 option.js
[2016-06-22 01:35:06.766] [INFO] server - 加载数据库 renewCode.js
[2016-06-22 01:35:06.776] [INFO] server - 加载数据库 server.js
[2016-06-22 01:35:06.783] [INFO] server - 加载数据库 user.js
[2016-06-22 01:35:06.895] [INFO] server - 开始加载Express路由配置文件

/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27777
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)`

请问这是什么问题..

谢谢

**Comment by gyteng** [comment]
应该是无法连接数据库，你的mongodb是否配置错了？

**Comment by XOXoNone** [comment]
抱歉是我自己的问题忘记启动mongod了...然后运行后出现了以下错误信息:

> Failed to instantiate module LoginApp due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.2.29/$injector/modulerr?p0=...)
    at Error (native)
    at http://xxx:6003/libs/angular/angular.min.js:6:450
    at http://xxx:6003/libs/angular/angular.min.js:34:97
    at r (http://xxx:6003/libs/angular/angular.min.js:7:290)
    at e (http://xxx:6003/libs/angular/angular.min.js:33:207)
    at http://xxx:6003/libs/angular/angular.min.js:33:284
    at r (http://xxx:6003/libs/angular/angular.min.js:7:290)
    at e (http://xxx:6003/libs/angular/angular.min.js:33:207)
    at dc (http://xxx:6003/libs/angular/angular.min.js:36:309)
    at c (http://xxx:6003/libs/angular/angular.min.js:18:170

是不是和我之前执行bower install的时候 安装了错误的版本导致的?

> Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#~1.2.5 which resolved to 1.2.29 and is required by angular-qr#0.2.0
    2) angular#1.x which resolved to 1.2.29 and is required by angular-chart.js#0.10.2
    3) angular#1.5.7 which resolved to 1.5.7 and is required by angular-animate#1.5.7, angular-aria#1.5.7, angular-messages#1.5.7
    4) angular#^1.0.8 which resolved to 1.5.7 and is required by angular-ui-router#0.2.18
    5) angular#^1.4.8 which resolved to 1.5.7 and is required by angular-material#1.0.9
Prefix the choice with ! to persist it to bower.json
? Answer 1

**Comment by gyteng** [comment]
选angular 1.5.7，可以把bower_components文件夹删除后重新bower install

2016-06-22 11:55 GMT+08:00 XOXoNone <notifications@github.com>:
