### ISSUE TITLE
Alipay Plugin Error

### ISSUE THREAD

**Issue by tyadan** [shadowsocks/shadowsocks-manager#180]
已经按照wiki，申请并开通了收款码，生成了RSA(SHA1)密钥，上传了公钥，并把生成的私钥和网页上的支付宝公钥填写到了配置文件中，但是后台依旧报如下错误：

{ message: '生成请求签名时错误',
  info: 
   Error: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
       at Error (native)
       at Sign.sign (crypto.js:283:26)
       at Object.getSign (/root/shadowsocks-manager/node_modules/alipay-ftof/lib/signHelper.js:56:27)
       at ex (/root/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:67:32)
       at Object.execute (/root/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:49:16)
       at Promise (/root/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:107:11)
       at alipay_f2f.createQRPay (/root/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:57:13)
       at Object.<anonymous> (/root/shadowsocks-manager/plugins/alipay/index.js:37:35)
       at next (native)
       at step (/root/shadowsocks-manager/plugins/alipay/index.js:1:191)
       at /root/shadowsocks-manager/plugins/alipay/index.js:1:361 }

**Comment by gyteng** [comment]
应该是你填的格式错了

tyadan <notifications@github.com>于2017年4月8日 周六02:25写道：

**Comment by cokebar** [comment]
私钥格式不对

**Comment by 873314461** [comment]
我也遇到了这个问题，楼主怎么解决的啊？

**Comment by tyadan** [comment]
我最后是手动修改alipay-ftof中的alipay_f2f.js，然后把公钥私钥按照格式写入就OK了，在配置文件中搞怎么都没搞定

**Comment by tyadan** [comment]
我最后是手动修改alipay-ftof中的alipay_f2f.js，然后把公钥私钥按照格式写入就OK了，在配置文件中搞怎么都没搞定

**Comment by DuLerWeil** [comment]
我出的是下面的错误

> { message: '生成请求签名时错误',
  info: 
   Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
       at Error (native)
       at Sign.sign (crypto.js:286:26)
       at Object.getSign (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/signHelper.js:56:27)
       at ex (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:67:32)
       at Object.execute (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:49:16)
       at Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:123:11)
       at alipay_f2f.createQRPay (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:72:13)
       at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:69:37)
       at next (native)
       at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:3:191)
       at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:3:361 }
