### ISSUE TITLE
验证码无法发送怎么办？

### ISSUE THREAD

**Issue by do1234** [shadowsocks/shadowsocks-manager#194]
### What version of shadowsocks-manager are you using?
不清楚，用这个命令安装的   npm i -g shadowsocks-manager

### What operating system are you using?
debain8*64

### What version of Node.js are you using?
Node.js 6.x

### What did you do?
email:
        use: true
        username: '0000707@qq.com'
        password: 's1'
        host: 'smtp.qq.com'
开放了端口：80 25 465

### What did you expect to see?
正常发送邮件

### What did you see instead?
无法发送邮件

### What is your config in detail (with all sensitive info masked)?
[2017-04-16 12:42:47.343] [ERROR] email - Send code fail: Error: Connection timeout
[2017-04-16 12:42:47.345] [ERROR] webgui - { Error: Connection timeout
    at SMTPConnection._formatError (/usr/lib/node_modules/shadowsocks-manager/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._onError (/usr/lib/node_modules/shadowsocks-manager/node_modules/smtp-connection/lib/smtp-connection.js:514:16)
    at SMTPConnection.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/smtp-connection/lib/smtp-connection.js:236:14)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', command: 'CONN' }

**Comment by gyteng** [comment]
这个错误很明显嘛 `Connection timeout`

**Comment by do1234** [comment]
请问有什么解决的办法吗？

**Comment by gyteng** [comment]
可能是你的防火墙问题

**Comment by do1234** [comment]
谢谢你，群里有人帮忙解决了。改用foxmail就好

**Comment by k1er** [comment]
@do1234 请问你用foxmail是怎么解决的，我用的是foxmail,也是timeout
