### ISSUE TITLE
Cannot access Internet while using shadowsocks-manager

### ISSUE THREAD

**Issue by Triple-Z** [shadowsocks/shadowsocks-manager#199]
### What version of shadowsocks-manager are you using?

shadowsocks-manager 0.6.5

### What operating system are you using?

CentOS 7

### What version of Node.js are you using?

v6.9.1

### What version of shadowsocks are you using?

v2.8.2 (Python)

### What did you do?

Start the shadowsocks, shadowsocks-manager client and server, also add several port (4616, 8889, 23333) to WebGUI.

### What did you expect to see?

Can access http://google.com from client.

### What did you see instead?

Error connection closed.

### What is your config in detail (with all sensitive info masked)?

When I look up shadowsocks server log, I find that there is a large amout of `ERROR` like:
```
2017-04-25 09:38:33 ERROR    server already exists at 23.83.249.226:4616
2017-04-25 09:38:33 ERROR    server already exists at 23.83.249.226:8889
2017-04-25 09:38:33 ERROR    server already exists at 23.83.249.226:23333
2017-04-25 09:39:33 ERROR    server already exists at 23.83.249.226:4616
2017-04-25 09:39:33 ERROR    server already exists at 23.83.249.226:8889
2017-04-25 09:39:33 ERROR    server already exists at 23.83.249.226:23333

```

And I find this in the client log:
```
[2017-04-25 17:40:17] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:17] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:17] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:17] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:21] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:21] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:21] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:21] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:21] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:21] testtest (23.83.249.226:8889) timed out
[2017-04-25 17:40:25] testtest (23.83.249.226:8889) timed out
```

The traffic in WebGUI is always **zero**.

I want to figure out whether I  am wrong or a bug in this version.

Thanks for your effort.

**Comment by Triple-Z** [comment]
```
[2017-04-25 09:44:00.003] [ERROR] system - { code: 1 }
[2017-04-25 09:44:00.003] [ERROR] flowSaver - Error: ssmgr[s] return an error code
    at receiveData.then.message (/usr/local/nodejs/node-v6.9.1-linux-x64/lib/node_modules/shadowsocks-manager/lib/services/manager.js:82:18)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

ERROR from manager-server.

**Comment by gyteng** [comment]
show me the full steps you run
Triple Z <notifications@github.com>于2017年4月25日 周二17:46写道：

**Comment by Triple-Z** [comment]
- Start the ss-manager client
    ssmgr -c /etc/.ssmgr/ss.yml
- Start the ss-manager server
    ssmgr -c /etc/.ssmgr/webgui.yml
- Start the shadowsocks server
    ssserver -c /etc/shadowsocks.json --manager-address 127.0.0.1:4000

**Comment by gyteng** [comment]
and the details of shadowsocks.json

Triple Z <notifications@github.com>于2017年4月25日 周二18:12写道：

**Comment by Triple-Z** [comment]
`shadowsocks.json` @gyteng 
```
{
    "server":"23.83.249.226",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "4616":"wwwwww",
        "9876":"wwwwww",
        "2341":"wwwwww",
        "5753":"wwwwww",
        "3546":"wwwwww"
    },
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":false
}
```

**Comment by gyteng** [comment]
you don't have to add the port in "port_password", ss-manager
is recommended to use.

2017-04-25 19:43 GMT+08:00 Triple Z <notifications@github.com>:
