### ISSUE TITLE
支付宝问题

### ISSUE THREAD

**Issue by shom** [shadowsocks/shadowsocks-manager#203]
### What version of shadowsocks-manager are you using?
v0.6.7

### What operating system are you using?
debian jessie

### What version of Node.js are you using?
6.10.2

### What did you do?
今天按V2帖子里的扫码开通，但是支付宝支付失败

### What did you expect to see?
如何解决这个问题？

### What did you see instead?
{ message: '生成请求签名时错误',
  info:
   Error: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag
       at Error (native)
       at Sign.sign (crypto.js:283:26)
       at Object.getSign (/home/pi/git/shadowsocks-manager/node_modules/alipay-ftof/lib/signHelper.js:56:27)
       at ex (/home/pi/git/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:67:32)
       at Object.execute (/home/pi/git/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:49:16)
       at Promise (/home/pi/git/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:109:11)
       at alipay_f2f.createQRPay (/home/pi/git/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:59:13)
       at Object.<anonymous> (/home/pi/git/shadowsocks-manager/plugins/alipay/index.js:37:35)
       at next (native)
       at step (/home/pi/git/shadowsocks-manager/plugins/alipay/index.js:1:191)
       at /home/pi/git/shadowsocks-manager/plugins/alipay/index.js:1:361 }
[2017-04-30 09:58:27.782] [ERROR] express - [undefined] POST 403 18ms /api/user/order/qrcode

### What is your config in detail (with all sensitive info masked)?
  alipay:
    use: true
    appid: 2017043007062094
    notifyUrl: 'http://104.238.150.201:8081/callback'
    merchantPrivateKey: 'MIIEvgIB..........................................................XI3NNakbaC/wsh'
    alipayPublicKey: 'MIIBIjA..........................................................................AQAB'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

**Comment by shom** [comment]
密钥生成格式选错了，应该选PKCS1
