### ISSUE TITLE
GUI Web - ER_DUP_KEYNAME

### ISSUE THREAD

**Issue by tath105** [shadowsocks/shadowsocks-manager#204]
Background:
first time running "ssmgr -c ~/.ssmgr/webgui.yml"

- The SQLite didn't exist before running the above command
- The MySQL is a brand new database.

====SQLite====
[2017-05-05 05:23:54.034] [ERROR] system - { Error: create index "index" on "saveFlow5min" ("time", "port") - SQLITE_ERROR: index index already exists
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }

====MySQL====
[2017-05-05 05:25:16.530] [ERROR] system - { Error: ER_DUP_KEYNAME: Duplicate key name 'index'
    at Query.Sequence._packetToError (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    --------------------
    at Protocol._enqueue (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:208:25)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/runner.js:193:19)
    at Runner.tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
  code: 'ER_DUP_KEYNAME',
  errno: 1061,
  sqlState: '42000',
  index: 0 }

**Comment by gyteng** [comment]
maybe version 0.6.9 will fix it
