### ISSUE TITLE
Issues with Alipay && put icon on screen with Safari on iOS 10

### ISSUE THREAD

**Issue by nylqd** [shadowsocks/shadowsocks-manager#211]
### What version of shadowsocks-manager are you using?
0.6.24

### What operating system are you using?
macOS sierra

### What version of Node.js are you using?
v6.10.2

#### alipay
- use sign tool from alipay, generate PKCS1 type 2048 bit RSA key, set bothRSA2(SHA256) and RSA(SHA1) on alipay develop platform
- set alipayPublicKey with key generate from alipay with RSA(SHA1) 
#### share to main screen
- open web page in Safari on iOS 10， share icon to main screen
- open icon on main icon, got **cannot GET /undefinded**

### What did you expect to see?
- alipay
payment qrcode?
- share to main screen
open web page by open icon on main screen?

### What did you see instead?
- alipay
**生成支付订单出错，请稍后再试**
- share to main screen 
**cannot GET /undefinded**

### What is your config in detail (with all sensitive info masked)?
```
  alipay:
    use: true
    appid: 2017052...
    notifyUrl: ''
    merchantPrivateKey: 'MIIEowIB...'
    alipayPublicKey: 'MIGfMA0GCS...'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
```

### webgui.log attached here
```
{ message: '生成请求签名时错误',
  info:
   Error: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
       at Error (native)
       at Sign.sign (crypto.js:283:26)
       at Object.getSign (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/signHelper.js:56:27)
       at ex (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:67:32)
       at Object.execute (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/aop.js:49:16)
       at Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:109:11)
       at alipay_f2f.createQRPay (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:59:13)
       at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:40:37)
       at next (native)
       at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:253)
       at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:423 }
[2017-05-21 07:42:57.275] [ERROR] express - [undefined] POST 403 16ms /api/user/order/qrcode
```

**Comment by gyteng** [comment]
it means there is something wrong with you key

2017-05-21 19:59 GMT+08:00 Ting Huang <notifications@github.com>:

**Comment by gyteng** [comment]
Can you take a screenshot about share to main screen page?

**Comment by nylqd** [comment]
![img_1283](https://cloud.githubusercontent.com/assets/3632490/26334982/72e36288-3f9b-11e7-83c5-072144c2c32a.PNG)
this is the only thing shows on the screen

**Comment by gyteng** [comment]
tell me the website and I can try in my phone

2017-05-23 9:38 GMT+08:00 Ting Huang <notifications@github.com>:

**Comment by nylqd** [comment]
the same issue happened on your site too...
i used the latest ios version 10.3.2, does it matter?

**Comment by gyteng** [comment]
My site works well  in my iPhone and Android phone

2017-05-23 9:52 GMT+08:00 Ting Huang <notifications@github.com>:

**Comment by nylqd** [comment]
that's wired .... i will check on it again, may be there are some other issues of my configuration
