### ISSUE TITLE
config.manager.address.split is not a function

### ISSUE THREAD

**Issue by milewski** [shadowsocks/shadowsocks-manager#213]
Guyssss.. i am getting this error straight out of the box

```
[2017-05-22 06:34:11.589] [INFO] system - System start.
[2017-05-22 06:34:12.226] [ERROR] system - TypeError: config.manager.address.split is not a function
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/services/server.js:11:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at shadowsocks (/usr/lib/node_modules/shadowsocks-manager/lib/init/loadServices.js:8:3)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/init/loadServices.js:14:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

im installing through this

```
FROM ubuntu:16.04
MAINTAINER gyteng <igyteng@gmail.com>
RUN apt-get update && \
    apt-get install curl git sudo -y && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get install -y nodejs && \
    npm i -g shadowsocks-manager && \
    git clone https://github.com/shadowsocks/shadowsocks-libev.git ~/shadowsocks && \
    mkdir -p ~/build-area/ && \
    cp ~/shadowsocks/scripts/build_deb.sh ~/build-area/ && \
    cd ~/build-area && \
    ./build_deb.sh
ENTRYPOINT ["/usr/bin/ssmgr"]
```

**Comment by gyteng** [comment]
Your node version?

**Comment by milewski** [comment]
```
root@hostname:~/.ssmgr# node -v
v6.10.3
```

**Comment by gyteng** [comment]
your config file is wrong

2017-05-22 14:41 GMT+08:00 Rafael Milewski <notifications@github.com>:

**Comment by milewski** [comment]
and i am trying to run this command

```
ssmgr --shadowsocks 127.0.0.1:6001 --manager 0.0.0.0:4001 -p 123456 -s
```

**Comment by gyteng** [comment]
try this:
ssmgr -t s -s 127.0.0.1:6001 -m 0.0.0.0:4001 -p 123456

2017-05-22 14:42 GMT+08:00 Rafael Milewski <notifications@github.com>:

**Comment by milewski** [comment]
works
