### ISSUE TITLE
重装好几场次都是这个错误Error: Cannot find module

### ISSUE THREAD

**Issue by yangxufang** [shadowsocks/shadowsocks-manager#217]
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Client_SQLite3._driver (/usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:219:26)
    at Client_SQLite3.Client (/usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:113:10)
    at new Client_SQLite3 (/usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)

**Comment by gyteng** [comment]
SQLite这个包经常因为网络问题或者是其他原因安装不成功，遇到你这种错误重新安装多次即可：

cd /usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/
shadowsocks-manager
rm -rf /usr/local/nodejs/node-v6.10.3-linux-x64/lib/node_modules/
shadowsocks-manager/node_modules
npm i

2017-05-26 10:34 GMT+08:00 yangxufang <notifications@github.com>:
