### ISSUE TITLE
ssmgr -c ss.yml运行错误提示

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/shadowsocks-manager#221]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.6.29

### What operating system are you using?
debian8+shadowsocks-python

### What version of Node.js are you using?
node.js 6.3 node.js 7.10

### What did you do?
运行ssmgr -c ss.yml --debug就报错。

### What did you expect to see?
正常运行不报错

### What did you see instead?
[2017-05-27 16:50:38.302] [INFO] system - System start.
[2017-05-27 16:50:38.430] [INFO] system - Config file path:  /root/.ssmgr/ss.yml
[2017-05-27 16:50:38.435] [INFO] system - { YAMLException: unexpected end of the stream within a single quoted scalar at line 9, column 1:

    ^
    at generateError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readSingleQuotedScalar (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:558:3)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1336:13)
    at readBlockMapping (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1061:11)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1331:12)
    at readDocument (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1493:3)
    at loadDocuments (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1549:5)
    at load (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1566:19)
    at Object.safeLoad (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1584:10)
  name: 'YAMLException',
  reason: 'unexpected end of the stream within a single quoted scalar',
  mark:
   Mark {
     name: null,
     buffer: 'type: s\nempty: false\nshadowsocks:\n  address: 127.0.0.1:8000\nmanager:\n  address: 0.0.0.0:8001\n  password: \'123456\'\ndb: \'ss.sqlite\n\u0000',
     position: 129,
     line: 8,
     column: 0 },
  message: 'unexpected end of the stream within a single quoted scalar at line 9, column 1:\n    \n    ^' }
[2017-05-27 16:50:38.444] [ERROR] system - Caught exception: TypeError: Path must be a string. Received undefined

### What is your config in detail (with all sensitive info masked)?
我用的是python版本，ss执行的命令行是：/usr/bin/python /usr/local/bin/ssserver -c /etc/shadowsocks.json --manager-address 127.0.0.1:8000 -d start

ss.yml内容
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:8000
manager:
  address: 0.0.0.0:8001
  password: '123456'
db: 'ss.sqlite

**Comment by gyteng** [comment]
配置文件语法有问题

hdstar2009 <notifications@github.com>于2017年5月27日 周六17:00写道：

**Comment by hdstar2009** [comment]
ss.yml的语法问题？我是copy自wiki上的。然后改变了下端口
