### ISSUE TITLE
SQL errors in console, flowHour and flowDay not updating

### ISSUE THREAD

**Issue by mklnz** [shadowsocks/shadowsocks-manager#228]
### What version of shadowsocks-manager are you using?
"version": "0.6.41"

### What operating system are you using?
Ubuntu 16.04 AMD64

### What version of Node.js are you using?
v6.10.3

### What did you do?
Ran ssmgr with MySQL backend
`bin/ssmgr -c ~/.ssmgr/webui.yml`

Servers: shadowsocks-libev 3.0.6, ss-manager mode

Log:

```
  errno: 1264,
  sqlState: '22003',
  index: 0 } } reason: { Error: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'flow' at row 4
    at Query.Sequence._packetToError (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
    --------------------
    at Protocol._enqueue (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/deploy/shadowsocks-manager/node_modules/mysql/lib/Connection.js:208:25)
    at /home/deploy/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/home/deploy/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/home/deploy/shadowsocks-manager/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/home/deploy/shadowsocks-manager/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/method.js:15:34)
    at /home/deploy/shadowsocks-manager/node_modules/knex/lib/runner.js:65:21
    at tryCatcher (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at /home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/deploy/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:512:31)
  code: 'ER_WARN_DATA_OUT_OF_RANGE',
```

**Comment by gyteng** [comment]
Delete your table and run again

**Comment by mklnz** [comment]
That's what I did initially, and no errors upon startup of server but as some time went on same thing happened. saveFlow & saveFlow 5min is working but 0 entries in saveFlowDay and saveFlowhour.

**Comment by gyteng** [comment]
you can try sqlite first.

**Comment by mklnz** [comment]
Do you want any more information to diagnose the root of the issue? I'm still hoping to use MySQL

**Comment by gyteng** [comment]
I think the problem is in your MySQL, maybe some parameter of MySQL in incorrect.

**Comment by mklnz** [comment]
Could this be related to 'only_full_group_by' setting?

**Comment by gyteng** [comment]
maybe.

server.js will use babel

**Comment by mklnz** [comment]
I found the problem, it looks like the default INT type for column flow is simply not enough, I've created a PR here:

https://github.com/shadowsocks/shadowsocks-manager/pull/229

**Comment by gyteng** [comment]
thx
