### ISSUE TITLE
求助：ss-libev+ss-manager+ss-webgui不能工作，似乎manager api没启成功

### ISSUE THREAD

**Issue by luggie1** [shadowsocks/shadowsocks-manager#239]
步骤如下：
1.安装shadowsocks-libev，用ss-server启动成功，且客户端连接该服务可正常使用；
2.安装shadowsocks-manager
4.启动ss-manager：

ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001

   2017-07-10 19:39:07 INFO: running from root user
5.创建ss.yml,内容如下：
type: s
empty: false
shadowsocks:
address: 127.0.0.1:6001
manager:
address: 0.0.0.0:4001
password: 'xxxxxx'
db: 'ss.sqlite'
然后，启动：

ssmgr -c ss.yml

/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/
[2017-07-10 19:42:35.325] [INFO] system - System start.

6.创建webgui.yml,内容如下：
type: m
empty: false

manager:
address: 公网地址:4001
password: 'xxxxxx'
plugins:
flowSaver:
use: true
user:
use: true
account:
use: true
pay:
hour:
price: 0.03
flow: 500000000
day:
price: 0.5
flow: 7000000000
week:
price: 3
flow: 50000000000
month:
price: 10
flow: 200000000000
season:
price: 30
flow: 200000000000
year:
price: 120
flow: 200000000000
email:
use: true
username: 'xxx'
password: 'xxx'
host: 'xxx'
webgui:
use: true
host: '0.0.0.0'
port: '80'
site: 'http://xxx'
gcmSenderId: 'xxx'
gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
alipay:
use: true
appid: 2015012108272442
notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
merchantPrivateKey: 'xxxxxxxxxxxx'
alipayPublicKey: 'xxxxxxxxxxx'
gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'
然后，启动：

ssmgr -c webgui.yml

/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/
[2017-07-10 19:47:33.702] [INFO] system - System start.
然后接着报如下错误：
[ERROR] account - Error: ssmgr[s] connection close [公网地址:4001]
at Socket.client.on (/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/services/manager.js:93:14)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at TCP._handle.close [as _onclose] (net.js:497:12)
[2017-07-10 19:51:00.022] [ERROR] flowSaver - Error: ssmgr[s] connection close [公网地址:4001]
at Socket.client.on (/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/services/manager.js:93:14)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at TCP._handle.close [as _onclose] (net.js:497:12)

麻烦帮忙看看，是哪里出问题了？万分感谢！
（webgui可以正常访问，但管理员添加新服务器不成功，应该也是上面原因导致）

**Comment by gyteng** [comment]
telnet看添加的服务器端口开了没

**Comment by luggie1** [comment]
端口可以telnet通的。
现在我把~/.ssmgr/下的所有sqlite文件都删了，然后重启，似乎没报那个错了，但添加服务器失败：

这个是添加端口已存在的ss服务报错
[2017-07-11 14:59:57.589] [ERROR] system - { Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Error: connect to ssmgr[s] fail  [公网地址:9000]
    at Socket.client.on.err (/ss/installpkg/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/services/manager.js:97:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2017-07-11 14:59:57.597] [ERROR] express - [undefined] POST 403 12ms /api/admin/server

这个是添加端口不存在的服务报错：
[2017-07-11 15:01:58.871] [ERROR] system - { Error: connect ECONNREFUSED 公网地址:9009
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '公网地址',
  port: 9009 }
Error: connect to ssmgr[s] fail  [公网地址:9009]
    at Socket.client.on.err (/ss/installpkg/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/services/manager.js:97:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[2017-07-11 15:01:58.886] [ERROR] express - [undefined] POST 403 17ms /api/admin/server

**Comment by gyteng** [comment]
不是很明白你的意思，建议你到tg群里问一下

luggie1 <notifications@github.com>于2017年7月11日 周二15:04写道：

**Comment by luggie1** [comment]
删空数据库后，重启各程序，然后在web页面上创建管理员ok，然后新增服务器失败，错误就是上面那些

**Comment by luggie1** [comment]
ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:9000
请问这命令中的端口号就是ss-server配置文件中的端口号吗？（我用的shadowsocks-libev）

**Comment by luggie1** [comment]
gyteng，请问这个webgui可以通过网页新增服务端口吗？网页上新增一个ss端口号，会自动启动一个新的ss-server进程吗？（shadowsocks-libev）

**Comment by gyteng** [comment]
请到tg群提问

**Comment by luggie1** [comment]
请问tg群是什么？
