### ISSUE TITLE
当面付出错，没有出错原因

### ISSUE THREAD

**Issue by naiwa** [shadowsocks/shadowsocks-manager#241]
今天一天我先后使用了Ubuntu14、Debian7、CentOS7测试、Node6/8，都试过了，都是这个东西。
到底什么原因啊？
```
[2017-07-14 06:02:29.466] [ERROR] express - [undefined] POST 403 36ms /api/user/order/qrcode
{ message: '��Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:109:11)
       at alipay_f2f.createQRPay (/usr/lib/node_modules/shadowsocks-manager/node_modules/alipay-ftof/lib/alipay_f2f.js:59:13)
       at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:44:37)
       at next (native)
       at step (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:253)
       at /usr/lib/node_modules/shadowsocks-manager/lib/plugins/alipay/index.js:1:423 }
[2017-07-14 06:12:51.520] [ERROR] express - [undefined] POST 403 9ms /api/user/order/qrcode
```

**Comment by naiwa** [comment]
中文错误信息不正常输出的问题。呵呵呵

**Comment by gyteng** [comment]
没有错误信息我也帮不了你，请检查你服务器的编码设置，或者到tg群里问一下有没有人遇到类似的问题

2017-07-25 10:20 GMT+08:00 奶爸 <notifications@github.com>:

**Comment by naiwa** [comment]
@gyteng 已经解决了 [Node.js初探那些坑](http://niubi.pw/post/2017-07-15/Node.js%E5%88%9D%E6%8E%A2%E9%82%A3%E4%BA%9B%E5%9D%91.html)

**Comment by gyteng** [comment]
究竟是什么情况造成的，你能复现吗？

2017-07-27 9:38 GMT+08:00 奶爸 <notifications@github.com>:

**Comment by yl5006** [comment]
可用当面付不用电脑网页支付解决支付功能么？
