### ISSUE TITLE
webgui - express server error: Error: listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by huzhihao2002** [shadowsocks/shadowsocks-manager#242]
按照wiki步骤安装完成后，
启动ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:4000`
`ssmgr -c ss.yml`
再启动 `ssmgr -c webgui.yml`
就报告如下错误：
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-07-15 23:22:47.249] [INFO] system - System start.
[2017-07-15 23:22:51.098] [_ERROR_] webgui - express server error: Error: listen EACCES 0.0.0.0:80
电脑也重启了，错误依然存在

- `node -v`
 `v6.11.1`

- shadowsocks-libev

- `/usr/lib
└── shadowsocks-manager@0.7.11 
`
- `ubuntu 16.04 bit 64`

**Comment by gyteng** [comment]
80端口没权限吧，加sudo

2017-07-15 23:37 GMT+08:00 huzhihao2002 <notifications@github.com>:

**Comment by huzhihao2002** [comment]
你是对的。加了sudo打开了
开始又出现连接失败的情况
`
~/.ssmgr$ sudo **ssmgr -c webgui.yml** 
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-07-16 08:50:20.637] [INFO] system - System start.
[2017-07-16 08:50:42.351] [ERROR] system - { **Error: connect ECONNREFUSED 1.1.1.1:4001**
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '1.1.1.1',
  port: 4001 }
[2017-07-16 08:50:42.374] [ERROR] flowSaver - connect to server 123456@1.1.1.1:4001 fail.
`

所有配置是默认的

**Comment by gyteng** [comment]
请根据实际情况调整配置文件里的ip地址，另外有不懂的问题可以到telegram交流群里提问
