### ISSUE TITLE
0.7.13升级0.8.3无法启动

### ISSUE THREAD

**Issue by Coolkids** [shadowsocks/shadowsocks-manager#246]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
0.8.3

### What operating system are you using?
ubuntu16.04

### What version of Node.js are you using?
v6.11.1

### What is your config in detail (with all sensitive info masked)?

有bug:

[2017-07-28 16:52:27.209] [ERROR] system - Error: Vapid private key should be 32 bytes long when decoded.
    at Object.validatePrivateKey (/usr/lib/node_modules/shadowsocks-manager/node_modules/web-push/src/vapid-helper.js:88:11)
    at Object.WebPushLib.setVapidDetails (/usr/lib/node_modules/shadowsocks-manager/node_modules/web-push/src/web-push-lib.js:60:17)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/push.js:9:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:4:10)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/home.js:11:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

[2017-07-28 17:15:09.137] [ERROR] system - { Error: alter table webguiSetting modify column value varchar(16384) - SQLITE_ERROR: near "modify": syntax error
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }

[2017-07-28 17:16:05.824] [ERROR] system - TypeError: Cannot read property 'mode' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/paypal/index.js:13:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:4:10)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/user.js:281:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by gyteng** [comment]
请先退回旧版本，待修复成可以平滑升级的版本

Coolkid <notifications@github.com>于2017年7月28日 周五17:26写道：

**Comment by Coolkids** [comment]
嗯 我已经回滚了 3Q

**Comment by gyteng** [comment]
出现这个问题的原因在于新版没有对某些可省略的参数做处理

Coolkid <notifications@github.com>于2017年7月28日 周五17:29写道：
