### ISSUE TITLE
fail to run ssmgr

### ISSUE THREAD

**Issue by haijohn** [shadowsocks/shadowsocks-manager#257]
after run `npm i -g shadowsocks-manager` , ssmgr is installed but fail to run, error traceback:
process.chdir(lib);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (/root/shadowsocks-manager/bin/ssmgr:7:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

node version is v6.11.1
OS: Ubuntu 16.10 x64

**Comment by gyteng** [comment]
show me the install log
