### ISSUE TITLE
使用freeAccount出现ECONNREFUSED 错误

### ISSUE THREAD

**Issue by Zweib** [shadowsocks/shadowsocks-manager#279]
### What version of shadowsocks-manager are you using?
the latest

### What operating system are you using?
centOS 6.5

### What version of Node.js are you using?
6.11.1

### What did you do?
try to run shadowsocks-manager with freeAcount plugins:
>ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001
>ssmgr -c free.yml

### What did you expect to see?
一个月前配的时候可以运行的，然后今天VPS maintainance再登上去操作一遍发现开不了orz
lsof|grep 6002确保端口未占用

### What did you see instead?
[root@li1674-210 shadowsocks-manager]# ssmgr -c free.yml --debug
/usr/local/node/6.11.1/lib/node_modules/shadowsocks-manager/lib/
[2017-09-02 03:58:23.129] [INFO] system - System start.
[2017-09-02 03:58:23.317] [INFO] system - Config file path:  /root/.ssmgr/free.yml
[2017-09-02 03:58:23.769] [INFO] system - Load plugin: flowSaver
[2017-09-02 03:58:23.772] [INFO] system - Load plugin db: flowSaver/db/saveFlow.js
[2017-09-02 03:58:23.773] [INFO] system - Load plugin db: flowSaver/db/saveFlow5min.js
[2017-09-02 03:58:23.775] [INFO] system - Load plugin db: flowSaver/db/saveFlowDay.js
[2017-09-02 03:58:23.776] [INFO] system - Load plugin db: flowSaver/db/saveFlowHour.js
[2017-09-02 03:58:23.777] [INFO] system - Load plugin db: flowSaver/db/server.js
[2017-09-02 03:58:23.779] [INFO] system - Load plugin: email
[2017-09-02 03:58:23.779] [INFO] system - Load plugin db: email/db/email.js
[2017-09-02 03:58:23.780] [INFO] system - Load plugin: freeAccount
[2017-09-02 03:58:23.781] [INFO] system - Load plugin db: freeAccount/db/freeAccount.js
[2017-09-02 03:58:23.800] [INFO] system - Load plugin index: email/index
[2017-09-02 03:58:23.863] [INFO] system - Load plugin index: freeAccount/index
[2017-09-02 03:58:24.037] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:6002
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6002 }
[2017-09-02 03:58:24.045] [ERROR] system - Caught exception: TypeError: Cannot read property 'host' of undefined
[2017-09-02 03:58:24.046] [ERROR] system - Caught exception: TypeError: Cannot read property 'host' of undefined
[2017-09-02 03:58:24.056] [ERROR] system - { Error: connect ECONNREFUSED 127.0.0.1:6002
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6002 }
[2017-09-02 03:58:24.057] [ERROR] flowSaver - connect to server 123456@127.0.0.1:6002 fail.

#### free.yml
type: m
empty: false
shadowsocks:
  address: 127.0.0.1:6001
manager:
  address: 127.0.0.1:6002
  password: '123456'
plugins:
  flowSaver:
    use: true
  email:
    use: true
    username: 'dollsmind@qq.com'
    password: 'xxxxxxxxxxxxxxxx'
    host: 'smtp.qq.com'
  freeAccount:
    use: true
    host: 'xxx.xxx.xxx.xxx'
    port: 80
    managerPassword: 'xxxxxxxx''
    shadowsocks:
      method: aes-256-cfb
      startPort: 55000
      endPort: 56000
      flow: 500
      time: 180
    limit:
      user:
        day: 0
        week: 0
        month: 0
      global:
        day: 0
        week: 0
        month: 0

db: 'free.sqlite'

#### default.yml
type: s
empty: false

shadowsocks:
  address: 127.0.0.1:6001

manager:
  address: 0.0.0.0:6002
  password: '123456'

db: 'db.sqlite'

**Comment by Zweib** [comment]
今天起来试了一下又可以了。。
nohup ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001 &
pm2 --name "ssmgr-default" -f start ssmgr -x -- -c default.yml
pm2 --name "ssmgr-free" -f start ssmgr -x -- -c free.yml
