### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by samping** [shadowsocks/shadowsocks-manager#281]
[2017-09-04 08:38:28.871] [ERROR] account - TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at /root/shadowsock-manager/plugins/account/checkAccount.js:235:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
麻烦解决一下这个bug

**Comment by gyteng** [comment]
请按照给定的模板填写issue内容并且说明如何重现这个bug

2017-09-04 16:40 GMT+08:00 samping <notifications@github.com>:
