### ISSUE TITLE
 ERROR    server already exists

### ISSUE THREAD

**Issue by Randy000** [shadowsocks/shadowsocks-manager#285]
### What version of shadowsocks-manager are you using?

shadowsocks-manager 0.8.64

### What operating system are you using?

Ubuntu 14.04.5 LTS (GNU/Linux 4.0.2-x86_64-linode56 x86_64)

### What version of Node.js are you using?

v6.11.2

### What did you do?

从win8.1 64系统，运行Shadowsocks-4.0.5，打开chrome（60.0.3112.113） 观看youtube的各种视频。然后shadowsocks(python-3.0.0)后端一直报以下的error，而且是重复提示同一段error。

### What did you expect to see?
不想看到ss后端的error信息。太多了。频繁出现同样的error
如果是警告信息还好。这个应该是个问题吧。我搜了下这个项目的issue，也搜了gogole。没找到任何解决方案。请作者帮我看下，谢谢:)

### What did you see instead?

randy@r*******d:~$ ssserver --manager-address 127.0.0.1:6001 -m chacha20-ietf-poly1305  -q
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:30063
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:39673
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53365
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53369
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53373
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53376
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53384
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53392
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53393
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53420
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53421
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53425
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53426
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53439
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53444
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53455
2017-09-07 16:08:00 ERROR    server already exists at 0.0.0.0:53456
^CTraceback (most recent call last):
  File "/usr/local/bin/ssserver", line 11, in <module>
    load_entry_point('shadowsocks==3.0.0', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/server.py", line 54, in main
    manager.run(config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 199, in run
    Manager(config).run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/manager.py", line 195, in run
    self._loop.run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/eventloop.py", line 198, in run
    events = self.poll(TIMEOUT_PRECISION)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks/eventloop.py", line 167, in poll
    events = self._impl.poll(timeout)
KeyboardInterrupt

randy@r*******d:~$ cd shadowsocks-manager/
randy@r*******d:~/shadowsocks-manager$ node ~/shadowsocks-manager/server.js -c ~/.ssmgr/ss.yml --debug
use babel-core/register
[2017-09-07 16:07:16.058] [INFO] system - System start.
[2017-09-07 16:07:16.242] [INFO] system - Config file path:  /home/randy/.ssmgr/ss.yml
[2017-09-07 16:07:17.486] [INFO] system - server listen on 0.0.0.0:4001
^C
randy@r*******d:~/shadowsocks-manager$ node ~/shadowsocks-manager/server.js -c ~/.ssmgr/ss.yml --debug
use babel-core/register
[2017-09-07 16:07:45.473] [INFO] system - System start.
[2017-09-07 16:07:45.663] [INFO] system - Config file path:  /home/randy/.ssmgr/ss.yml
[2017-09-07 16:07:46.849] [INFO] system - server listen on 0.0.0.0:4001
[2017-09-07 16:08:10.075] [INFO] system - Receive flow from shadowsocks: (python)
{
  "53376": 1544
}
[2017-09-07 16:08:11.808] [INFO] system - { command: 'list' }

randy@r*******d:~/shadowsocks-manager$ node /home/randy/shadowsocks-manager/server.js -c /home/randy/.ssmgr/webgui.yml --debug
use babel-core/register
[2017-09-07 16:08:00.795] [INFO] system - System start.
[2017-09-07 16:08:00.970] [INFO] system - Config file path:  /home/randy/.ssmgr/webgui.yml
[2017-09-07 16:08:01.900] [INFO] system - Load plugin: flowSaver
[2017-09-07 16:08:01.902] [INFO] system - Load plugin db: flowSaver/db/saveFlow.js
[2017-09-07 16:08:01.950] [INFO] system - Load plugin db: flowSaver/db/saveFlow5min.js
[2017-09-07 16:08:01.989] [INFO] system - Load plugin db: flowSaver/db/saveFlowDay.js
[2017-09-07 16:08:02.055] [INFO] system - Load plugin db: flowSaver/db/saveFlowHour.js
[2017-09-07 16:08:02.106] [INFO] system - Load plugin db: flowSaver/db/server.js
[2017-09-07 16:08:02.174] [INFO] system - Load plugin: user
[2017-09-07 16:08:02.175] [INFO] system - Load plugin db: user/db/user.js
[2017-09-07 16:08:02.217] [INFO] system - Load plugin: account
[2017-09-07 16:08:02.217] [INFO] system - Load plugin db: account/db/account.js
[2017-09-07 16:08:02.255] [INFO] system - Load plugin: email
[2017-09-07 16:08:02.255] [INFO] system - Load plugin db: email/db/email.js
[2017-09-07 16:08:02.298] [INFO] system - Load plugin: webgui
[2017-09-07 16:08:02.299] [INFO] system - Load plugin db: webgui/db/notice.js
[2017-09-07 16:08:02.362] [INFO] system - Load plugin db: webgui/db/push.js
[2017-09-07 16:08:02.397] [INFO] system - Load plugin db: webgui/db/setting.js
[2017-09-07 16:08:02.433] [INFO] system - Load plugin: alipay
[2017-09-07 16:08:02.434] [INFO] system - Load plugin db: alipay/db/alipay.js
[2017-09-07 16:08:02.525] [INFO] system - Load plugin index: user/index
[2017-09-07 16:08:02.760] [INFO] system - Load plugin index: email/index
[2017-09-07 16:08:03.026] [INFO] system - Load plugin index: account/index
[2017-09-07 16:08:03.773] [INFO] system - Load plugin index: webgui/index
[2017-09-07 16:08:05.323] [INFO] system - Load plugin index: alipay/index
[2017-09-07 16:08:05.328] [INFO] webgui - server start at 127.0.0.1:8080
[2017-09-07 16:08:05.359] [INFO] system - Load plugin index: flowSaver/index
[2017-09-07 16:08:11.772] [INFO] account - check account
[2017-09-07 16:08:12.288] [INFO] account - check account flow [Japan] 17
[2017-09-07 16:08:12.341] [INFO] account - check account flow [Hong Kong] 6

### What is your config in detail (with all sensitive info masked)?

**/home/randy/.ssmgr/ss.yml**

type: s
empty: false
shadowsocks:
  address: 127.0.0.1:6001

manager:
  address: 0.0.0.0:4001

  password: 'X******************4c'
db: 'ss.sqlite'

**/home/randy/.ssmgr/webgui.yml**

type: m
empty: false

manager:
  address: 10*.1**.1**.1**:4001
  password: 'X******************4c'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  email:
    use: true
    username: 'service@mg.r*******i.com'
    password: '********************'
    host: 'smtp.mailgun.org'
    # 这部分的邮箱和密码是用于发送注册验证邮件，重置密码邮件
  webgui:
    use: true
    host: '127.0.0.1'
    port: '8080'
    site: 'https://jp.r*******i.com'
    # cdn: 'http://xxx.com' # 静态资源cdn地址，可省略
    # googleAnalytics: 'UA-xxxxxxxx-x' # Google Analytics ID，可省略
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: true
    appid: 201***********6
    notifyUrl: 'https://jp.r*******i.com/api/user/alipay/callback'
    merchantPrivateKey: '**********'
    alipayPublicKey: '*********'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db:
  host: '127.0.0.1'
  user: 'randy'
  password: '********'
  database: '*********'

**Comment by gyteng** [comment]
使用问题请到tg群提问
