### ISSUE TITLE
使用 NPM 安装 SSMGR 问题

### ISSUE THREAD

**Issue by Triple-Z** [shadowsocks/shadowsocks-manager#291]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?

0.9.4
### What operating system are you using?

CentOS 7.3
### What version of Node.js are you using?

v6.11.3

### What did you do?

npm i -g shadowsocks-manager
### What did you expect to see?

Successfully install.

### What did you see instead?
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/.node-gyp/6.11.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/.node-gyp"
```

**Comment by Triple-Z** [comment]
可是我使用的是 root 用户运行的。

也尝试过 `chown -R /root/.nvm/versions/node/` ，并没有用。

**Comment by Triple-Z** [comment]
```
[root@host ~]# ssmgr
/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/lib/
[2017-10-02 13:56:08.399] [INFO] system - System start.
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Client_SQLite3._driver (/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:219:26)
    at Client_SQLite3.Client (/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:113:10)
    at new Client_SQLite3 (/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)

```

**Comment by cbwang2016** [comment]
从错误日志来看，尝试cd到/root/.nvm/versions/node/v6.11.3/lib/node_modules/shadowsocks-manager然后执行npm install sqlite3再运行试试

**Comment by Triple-Z** [comment]
@cbwang2016 并不行，最后通过重装 `Node.js` 解决了。

**Comment by Triple-Z** [comment]
解决方法：

到 shadowsocks-manager 目录下运行：
> npm install sqlite3 --unsafe-perm
