### ISSUE TITLE
npm install issure

### ISSUE THREAD

**Issue by wggwcn** [shadowsocks/shadowsocks-manager#324]
`root@VM_0_13_centos shadowsocks-manager]# npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> sqlite3@3.1.13 install /usr/local/src/node-v6.10.0/shadowsocks-manager/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build`

然后就卡着不动了~~~~

`[root@VM_0_13_centos shadowsocks-manager]# node server.js
use babel-core/register
[2017-11-11 09:40:57.071] [INFO] system - System start.
Knex: run
$ npm install sqlite3 --save
Error: /usr/local/src/node-v6.10.0/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node: ELF load command past end of file
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/src/node-v6.10.0/shadowsocks-manager/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/src/node-v6.10.0/shadowsocks-manager/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
`

**Comment by wggwcn** [comment]
然后我删除了 ghost-cli 然后再安装ghost-cli
npm un -g ghost-cli && npm i -g ghost-cli
系统貌似不动了。。

**Comment by gyteng** [comment]
跟 ghost-cli 没有关系
