### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by mostafaasadi** [shadowsocks/shadowsocks-manager#325]
### What version of shadowsocks-manager are you using?
`shadowsocks-manager 0.10.11`

### What operating system are you using?
`ubutnu 16.04`

### What version of Node.js are you using?
`v6.11.4`

### What did you do?
I start shadowsocks server , it is ok and I  can connect to it
I start manager as type s seccsessfully
I try to start manager with type m for webgui but give me Error

### What did you expect to see?
the web gui 

### What did you see instead?
```mostafa@ubuntu:~$ sudo ssmgr -c wg.yml --debug     
[sudo] password for mostafa: 
/usr/lib/node_modules/shadowsocks-manager/lib/
[2017-11-11 17:57:56.781] [INFO] system - System start.
[2017-11-11 17:57:56.955] [INFO] system - Config file path:  /home/mostafa/.ssmgr/wg.yml
[2017-11-11 17:57:57.353] [INFO] system - Load plugin: flowSaver
[2017-11-11 17:57:57.355] [INFO] system - Load plugin db: flowSaver/db/saveFlow.js
[2017-11-11 17:57:57.356] [INFO] system - Load plugin db: flowSaver/db/saveFlow5min.js
[2017-11-11 17:57:57.357] [INFO] system - Load plugin db: flowSaver/db/saveFlowDay.js
[2017-11-11 17:57:57.358] [INFO] system - Load plugin db: flowSaver/db/saveFlowHour.js
[2017-11-11 17:57:57.359] [INFO] system - Load plugin db: flowSaver/db/server.js
[2017-11-11 17:57:57.361] [INFO] system - Load plugin: user
[2017-11-11 17:57:57.361] [INFO] system - Load plugin db: user/db/user.js
[2017-11-11 17:57:57.362] [INFO] system - Load plugin: account
[2017-11-11 17:57:57.362] [INFO] system - Load plugin db: account/db/account.js
[2017-11-11 17:57:57.363] [INFO] system - Load plugin: macAccount
[2017-11-11 17:57:57.363] [INFO] system - Load plugin db: macAccount/db/macAccount.js
[2017-11-11 17:57:57.365] [INFO] system - Load plugin: webgui
[2017-11-11 17:57:57.365] [INFO] system - Load plugin db: webgui/db/notice.js
[2017-11-11 17:57:57.366] [INFO] system - Load plugin db: webgui/db/push.js
[2017-11-11 17:57:57.367] [INFO] system - Load plugin db: webgui/db/setting.js
[2017-11-11 17:57:57.382] [INFO] system - Load plugin index: user/index
[2017-11-11 17:57:57.397] [INFO] system - Load plugin index: account/index
[2017-11-11 17:57:57.435] [INFO] system - Load plugin index: macAccount/index
[2017-11-11 17:57:57.438] [INFO] system - Load plugin index: webgui/index
[2017-11-11 17:57:57.798] [ERROR] system - TypeError: Cannot read property 'type' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/email/index.js:17:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/home.js:12:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.appRequire.filePath (/usr/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/webgui/server/route.js:6:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
[2017-11-11 17:57:57.809] [INFO] webgui - server start at 0.0.0.0:8090
[2017-11-11 17:57:57.831] [INFO] system - Load plugin index: flowSaver/index
[2017-11-11 17:58:00.003] [INFO] account - check account 
```

### What is your config in detail (with all sensitive info masked)?

```
mostafa@ubuntu:~$ cat /etc/shadowsocks-libev/config.json 
{
    "server":"server public ip",
    "local_port":1080,
    "port_password": {
        "1111": "mostafa",
        "2222": "morteza"
},
    "timeout":600,
    "dns":"8.8.8.8",
    "method":"aes-256-cfb"
}
```

```
mostafa@ubuntu:~$ cat .ssmgr/config.yml 
type: s
shadowsocks:
  address: 127.0.0.1:1080
manager:
  address: 0.0.0.0:6002
  password: 'XXXX'
db: 'ss.sqlite' 
```

```
mostafa@ubuntu:~$ cat .ssmgr/wg.yml 
type: m

manager:
  address: 127.0.0.1:6002
  password: 'XXXX'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8090'
    site: 'http://my domain on that public server ip .ir'


db: 'webgui.sqlite' 
```

**Comment by gyteng** [comment]
Something wrong in your config file `wg.yml`

**Comment by mostafaasadi** [comment]
thank you for your response
there is my wg.yml , I create it according to the wiki and I can't find any problem 
do you see any mistake ? 

```
mostafa@ubuntu:~$ cat .ssmgr/wg.yml 
type: m

manager:
  address: 127.0.0.1:6002
  password: 'XXXX'

plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8090'
    site: 'http://my domain on that public server ip .ir'


db: 'webgui.sqlite' 
```

**Comment by gyteng** [comment]
Maybe the config file is not a correct yaml file, such as use tab or other reason.
Please ask question in telegram group when u met a problem about deploy.

**Comment by mostafaasadi** [comment]
thank tou 
I solve it and find problem 
the problem is that you should set all parametrs in yml fiel accordint to readme , just comment them or false them if you don't want them, but you must use all options. 
best regards
