### ISSUE TITLE
数据库中不增加Email库

### ISSUE THREAD

**Issue by shinozakiyui** [shadowsocks/shadowsocks-manager#326]
web能正常打开，但是发送注册邮件的时候报错，查看数据库后发现没有email这张表，卸载重装过后还是这样，用自带的那个sql也是找不到表

[root@shinozaki init]# node -v
v9.0.0

[2017-11-13 00:16:54.436] [ERROR] email - Send code fail: Error: select `remark` from `email` where `to` = '1@qq.com' and `type` = 'code' and `time` between 1510502814434 and 1510503414434 - ER_NO_SUCH_TABLE: Table 'SSW.email' doesn't exist
[2017-11-13 00:16:54.436] [ERROR] webgui - { Error: ER_NO_SUCH_TABLE: Table 'SSW.email' doesn't exist
    at Query.Sequence._packetToError (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:598:20)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_mysql@2.15.0@mysql/lib/Connection.js:208:25)
    at /usr/local/lib/node_modules/shadowsocks-manager/node_modules/_knex@0.12.9@knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_knex@0.12.9@knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_knex@0.12.9@knex/lib/client.js:197:17)
    at Runner.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_knex@0.12.9@knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)
    at Runner.query (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/method.js:15:34)
    at /usr/local/lib/node_modules/shadowsocks-manager/node_modules/_knex@0.12.9@knex/lib/runner.js:65:21
    at tryCatcher (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)
    at /usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/using.js:185:26
    at tryCatcher (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/_bluebird@3.5.1@bluebird/js/release/promise_array.js:144:14)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: 'Table \'SSW.email\' doesn\'t exist',
  sqlState: '42S02',
  index: 0,
  sql: 'select `remark` from `email` where `to` = \'1@qq.com\' and `type` = \'code\' and `time` between 1510502814434 and 1510503414434' }
[2017-11-13 00:16:54.441] [ERROR] express - [undefined] POST 403 10ms /api/home/code
[2017-11-13 00:17:00.002] [INFO] system - Receive flow from shadowsocks: (libev)
{}

show tables;
+----------------+
| Tables_in_SSW  |
+----------------+
| account        |
| account_plugin |
| command        |
| flow           |
| mac_account    |
| notice         |
| push           |
| saveFlow       |
| saveFlow5min   |
| saveFlowDay    |
| saveFlowHour   |
| server         |
| sessions       |
| webguiSetting  |
+----------------+
14 rows in set (0.00 sec)

**Comment by gyteng** [comment]
请贴出配置文件

2017-11-13 0:21 GMT+08:00 shinozakiyui <notifications@github.com>:

**Comment by shinozakiyui** [comment]
type: m
manager:
        address: 127.0.0.1:9988
        password: 'ss'
plugins:
        flowSaver:
                use: true
        account:
                use: true
        macAccount:
                use: true
        email:
                usee: true
                type: 'smtp'
                username: 'email@host'
                password: 'password'
                host: 'smtp.qq.com'
                port: '465'

        webgui:
                use: true
                host: '0.0.0.0'
                port: '9999'
                site: 'http://webside'
               

db:
   host: '127.0.0.1'
   port: '9985'
   user: 'sql'
   password: 'sql'
   database: 'SSW'

**Comment by gyteng** [comment]
配置文件错了，请参考Wiki里的写法

shinozakiyui <notifications@github.com>于2017年11月13日 周一18:10写道：

**Comment by shinozakiyui** [comment]
看到了。。输入错误一个。。
