### ISSUE TITLE
./ssmgr  --h failed

### ISSUE THREAD

**Issue by Hello-World-0X** [shadowsocks/shadowsocks-manager#344]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
ss python

### What operating system are you using?
cnetos
 7.4.1708
### What version of Node.js are you using?
9.3.0

### What did you do?
install shadowsocks-manager

### What did you see instead?
When I run ssmgr,some errors have happened.The infomation of console is in the space below

/usr/local/src/shadowsocks-manager/lib/
/usr/local/src/shadowsocks-manager/bin/ssmgr:7
process.chdir(lib);
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Object.<anonymous> (/usr/local/src/shadowsocks-manager/bin/ssmgr:7:9)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by gyteng** [comment]
use Node.js 6.x and reinstall it

2017-12-21 14:39 GMT+08:00 Hello-World-0X <notifications@github.com>:
