### ISSUE TITLE
Error: Cannot find module sqlite3 when starting ssmgr (Resolved)

### ISSUE THREAD

**Issue by duduluu** [shadowsocks/shadowsocks-manager#371]
### What version of shadowsocks-manager are you using?
0.13.5

### What operating system are you using?
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-109-generic x86_64)

### What version of Node.js are you using?
v8.9.4 or v6.*

### What did you do?
`# ssmgr -c ss.yml`

### What did you expect to see?
```bash
# ssmgr -c ss.yml -r libev:aes-256-gcm
/usr/lib/node_modules/shadowsocks-manager/lib/
[2018-03-02 03:14:37.120] [INFO] system - System start.
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:219:26)
    at Client_SQLite3.Client (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:113:10)
    at new Client_SQLite3 (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
```

### Resolved the problem by rebuild sqlite3
```bash
cd /usr/lib/node_modules/shadowsocks-manager/lib/
npm rebuild sqlite3
```

May add the solution to the document or wiki. :)

**Comment by damonYuan** [comment]
you can close it thend.
