### ISSUE TITLE
启动webgui出错了

### ISSUE THREAD

**Issue by blackier** [shadowsocks/shadowsocks-manager#380]
root@vultr:~# ssmgr -c ~/webgui.yml
/usr/lib/node_modules/shadowsocks-manager/lib/
[2018-03-17 04:14:02.692] [INFO] system - System start.
[2018-03-17 04:14:04.734] [ERROR] system - { Error: connect ECONNREFUSED 45.76.195.110:4001
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '45.76.195.110',
  port: 4001 }
[2018-03-17 04:14:04.744] [ERROR] flowSaver - connect to server mysssite@45.76.195.110:4001 fail.

**Comment by flyingOrange** [comment]
I have the same problem!
When I add a new server,an error jump out.The error log is 

[2018-10-31 15:07:57.414] [ERROR] system - { Error: connect ECONNREFUSED 104.129.182.2:4001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '104.129.182.2',
  port: 4001 }

How can I solve the problem?
