### ISSUE TITLE
SMTP time out,不能注册账号。

### ISSUE THREAD

**Issue by KickUasS** [shadowsocks/shadowsocks-manager#433]
### What version of shadowsocks-manager are you using?
0.19.6
### What operating system are you using?
Ubuntu 16.04
### What version of Node.js are you using?
v6.14.3
### What did you do?
注册新账户时发送邮箱验证码
### What did you see instead?
发送超时，错误记录如下
[2018-07-06 09:15:48.614] [INFO] system - System start.
[2018-07-06 09:18:05.642] [ERROR] email - Send code fail: Error: Connection timeout
[2018-07-06 09:18:05.644] [ERROR] webgui - { Error: Connection timeout
    at SMTPConnection._formatError (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._onError (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
    at Timeout._connectionTimeout.setTimeout (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/nodemailer/lib/smtp-connection/index.js:261:18)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', command: 'CONN' }
[2018-07-06 09:20:05.775] [ERROR] email - Send code fail: Error: Connection timeout
[2018-07-06 09:20:05.776] [ERROR] webgui - { Error: Connection timeout
    at SMTPConnection._formatError (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
    at SMTPConnection._onError (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
    at Timeout._connectionTimeout.setTimeout (/usr/local/lib/node_modules/shadowsocks-manager/node_modules/nodemailer/lib/smtp-connection/index.js:261:18)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', command: 'CONN' }

### What is your config in detail (with all sensitive info masked)?
在WEBGUI.YML里面SMTP配置如下：
 email:
    use: true
    type: 'smtp'
    username: 'xxxxxx（手工打码）@qq.com'
    password: 'zamgzgtydsiqbidi'
    host: 'smtp.qq.com'

结果就是无法注册账号，不用邮箱的话，能否注册账号呢？

**Comment by gyteng** [comment]
改用mailgun或者用支持smtp协议的vps来搭建

**Comment by KickUasS** [comment]
GCE的日本机房VPS，怎么看支持不支持SMTP？

**Comment by KickUasS** [comment]
OKAY,我在GCE文档里破案了，GCE确实是默认封堵SMTP出站流量的。
MAILGUN调用的话，能否给些指点，谢谢，纯新手

**Comment by cokebar** [comment]
@KickUasS Mailgun还是比较简单的，按照提示注册后，然后绑定信用卡就可以升级到10000/月的plan了（超10000会收费）
然后绑定自己的域名，添加MX、SPF记录等等一系列操作，跟着提示来就行；建议使用子域名，因为根域名的邮箱服务估计你绑到别的服务商了吧。
绑好后会得到你的API base url, API key，然后按照这里说的配置就行：
https://github.com/shadowsocks/shadowsocks-manager/wiki/WebGUI#%E4%BD%BF%E7%94%A8mailgun-api
