### ISSUE TITLE
Continuous disk writing at a high frequency

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#463]
### What version of shadowsocks-manager are you using?
0.25.X ( I've modified checkConfig.js to disable log file output)
one webgui(mode m) and several ssmgr(mode s) in different locations. Every mode s server opens about 20~30 ss ports.

### What operating system are you using?
Ubuntu 16.04/18.04

### What version of Node.js are you using?
8.11.4

### Problem
Continuous high rate disk writing was observed when ssmgr is running. (Both for mode s and mode m, and mode m has a much higher rate)
mode s ssmgr write to disk about every 5 second.
mode m webgui write to disk continuously.
a sqlite journal file appears and disappears, loop, at a very high frequency.

```
# When ssmgr webgui running
iotop -oP
```
![image](https://user-images.githubusercontent.com/9136591/45135727-a162db80-b1a9-11e8-8831-51844123f2bc.png)
ssmgr write to disk at a 40~50KB/s speed, continuously.

```
iostat:
Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
loop0             0.00         0.00         0.00          1          0
vda              34.73        22.02       318.43   14606391  211200400
```
And the rate is 30~40 times per second.

```
cat /proc/$pid/io
rchar: 11057234
wchar: 29409364
syscr: 48218
syscw: 46384
read_bytes: 0
write_bytes: 41672704
cancelled_write_bytes: 0
```
When ssmgr webgui run about 10min, it write to disk 29,409,364 bytes data, i.e., about 48KB/s. And it call the write/read command about 80/s.

And in the console log output, often SQL BUSY is observed.
This kind of continuously writing is also harmful to the disk.

### possible reasons
I think the possible reasons are:
ssmgr try to collect ss server status at a too high rate(maybe every few seconds as I observed).
And when webgui connect to many ss-server and the open port number is big, the rate can be much higher.

### Solution
1. Collect server status at a lower rate. It will be better if the rate can be customized by user .
2. Use memory cache or something to reduce the disk writing frequency.

**Comment by gyteng** [comment]
show the logs

**Comment by cokebar** [comment]
### mode m 
v 0.25.11

account
```
[2018-09-04 00:00:10.626] [INFO] account - check 46 accounts, 16503 ms
[2018-09-04 00:00:28.312] [INFO] account - check 50 accounts, 17685 ms
[2018-09-04 00:00:47.068] [INFO] account - check 47 accounts, 18756 ms
[2018-09-04 00:01:04.680] [INFO] account - check 50 accounts, 17612 ms
[2018-09-04 00:01:22.497] [INFO] account - check 47 accounts, 17816 ms
[2018-09-04 00:01:39.528] [INFO] account - check 49 accounts, 17030 ms
[2018-09-04 00:01:54.539] [INFO] account - check 41 accounts, 15011 ms
[2018-09-04 00:02:13.090] [INFO] account - check 48 accounts, 18551 ms
...
same lines continue
```

flowsaver
```
[2018-09-04 00:00:00.036] [INFO] flowSaver - Generate 5min flow, length: 8
[2018-09-04 00:00:00.037] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:01:00.016] [INFO] flowSaver - Generate day flow, length: 31
[2018-09-04 00:01:00.016] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:01:00.099] [INFO] flowSaver - Generate hour flow, length: 15
[2018-09-04 00:01:00.099] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:03:00.030] [ERROR] flowSaver - Error: ssmgr[s] return an error code [127.0.0.1:5775]
    at receiveData.then.message (/home/xxxxx/shadowsocks-manager/services/manager.js:75:18)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2018-09-04 00:05:00.015] [INFO] flowSaver - Generate 5min flow, length: 7
[2018-09-04 00:05:00.015] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:10:00.018] [INFO] flowSaver - Generate 5min flow, length: 5
[2018-09-04 00:10:00.018] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:15:00.019] [INFO] flowSaver - Generate 5min flow, length: 6
[2018-09-04 00:15:00.019] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:19:00.022] [ERROR] flowSaver - Error: ssmgr[s] return an error code [127.0.0.1:5775]
    at receiveData.then.message (/home/xxxxx/shadowsocks-manager/services/manager.js:75:18)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[2018-09-04 00:20:00.015] [INFO] flowSaver - Generate 5min flow, length: 6
[2018-09-04 00:20:00.016] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:25:00.018] [INFO] flowSaver - Generate 5min flow, length: 6
[2018-09-04 00:25:00.018] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:30:00.018] [INFO] flowSaver - Generate 5min flow, length: 6
[2018-09-04 00:30:00.018] [INFO] flowSaver - insert generate flow from 0 to 50
[2018-09-04 00:35:00.016] [INFO] flowSaver - Generate 5min flow, length: 7
[2018-09-04 00:35:00.017] [INFO] flowSaver - insert generate flow from 0 to 50
...
```

system
```
[2018-09-04 00:03:00.028] [ERROR] system - { code: 1 }
[2018-09-04 00:19:00.021] [ERROR] system - { code: 1 }
[2018-09-04 00:44:58.328] [ERROR] system - { code: 1 }
[2018-09-04 02:22:04.620] [ERROR] system - { code: 1 }
[2018-09-04 03:45:14.939] [ERROR] system - timeout
[2018-09-04 03:45:36.665] [ERROR] system - Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:707:40)
    at Socket.net.connect (/home/xxxxx/shadowsocks-manager/services/manager.js:60:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:10)
[2018-09-04 04:07:00.391] [ERROR] system - { code: 1 }
[2018-09-04 04:11:15.026] [ERROR] system - timeout
[2018-09-04 04:25:00.858] [ERROR] system - { code: 1 }
[2018-09-04 05:03:00.016] [ERROR] system - { code: 1 }
[2018-09-04 05:27:38.981] [ERROR] system - timeout
[2018-09-04 05:27:52.421] [ERROR] system - timeout
[2018-09-04 05:28:06.298] [ERROR] system - timeout
[2018-09-04 05:28:11.924] [ERROR] system - Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:707:40)
    at Socket.net.connect (/home/xxxxx/shadowsocks-manager/services/manager.js:60:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:10)
[2018-09-04 05:28:34.455] [ERROR] system - Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:707:40)
    at Socket.net.connect (/home/xxxxx/shadowsocks-manager/services/manager.js:60:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:10)
[2018-09-04 05:28:46.737] [ERROR] system - Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:707:40)
    at Socket.net.connect (/home/xxxxx/shadowsocks-manager/services/manager.js:60:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:10)
[2018-09-04 05:43:00.020] [ERROR] system - { code: 1 }
[2018-09-04 05:54:36.889] [ERROR] system - timeout
[2018-09-04 05:54:42.635] [ERROR] system - Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at Socket.Writable.write (_stream_writable.js:287:5)
    at Socket.write (net.js:707:40)
    at Socket.net.connect (/home/xxxxx/shadowsocks-manager/services/manager.js:60:14)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:10)
[2018-09-04 05:54:50.696] [ERROR] system - timeout
...
```

### mode s
v 0.25.11
```
[2018-09-04 00:00:00.000] [INFO] system - Receive flow from shadowsocks: (libev)
{}
[2018-09-04 00:00:00.001] [INFO] system - Receive flow from shadowsocks: (libev)
{}
[2018-09-04 00:00:00.058] [INFO] system - { command: 'flow', options: { clear: true } }
[2018-09-04 00:00:00.942] [INFO] system - { command: 'list' }
[2018-09-04 00:00:01.592] [INFO] system - { command: 'list' }
[2018-09-04 00:00:02.175] [INFO] system - { command: 'list' }
[2018-09-04 00:00:02.285] [INFO] system - { command: 'list' }
[2018-09-04 00:00:02.398] [INFO] system - { command: 'list' }
[2018-09-04 00:00:02.979] [INFO] system - { command: 'list' }
[2018-09-04 00:00:06.551] [INFO] system - { command: 'list' }
[2018-09-04 00:00:08.954] [INFO] system - { command: 'list' }
[2018-09-04 00:00:11.714] [INFO] system - { command: 'list' }
[2018-09-04 00:00:11.825] [INFO] system - { command: 'list' }
[2018-09-04 00:00:12.858] [INFO] system - { command: 'list' }
[2018-09-04 00:00:12.966] [INFO] system - { command: 'list' }
[2018-09-04 00:00:13.536] [INFO] system - { command: 'list' }
[2018-09-04 00:00:14.044] [INFO] system - { command: 'list' }
[2018-09-04 00:00:14.160] [INFO] system - { command: 'list' }
[2018-09-04 00:00:14.313] [INFO] system - { command: 'list' }
[2018-09-04 00:00:15.709] [INFO] system - { command: 'list' }
[2018-09-04 00:00:17.271] [INFO] system - { command: 'list' }
[2018-09-04 00:00:17.381] [INFO] system - { command: 'list' }
[2018-09-04 00:00:17.810] [INFO] system - { command: 'list' }
[2018-09-04 00:00:17.920] [INFO] system - { command: 'list' }
[2018-09-04 00:00:18.493] [INFO] system - { command: 'list' }
[2018-09-04 00:00:21.181] [INFO] system - { command: 'list' }
[2018-09-04 00:00:27.307] [INFO] system - { command: 'list' }
[2018-09-04 00:00:28.779] [INFO] system - { command: 'list' }
[2018-09-04 00:00:33.321] [INFO] system - { command: 'list' }
[2018-09-04 00:00:33.431] [INFO] system - { command: 'list' }
[2018-09-04 00:00:34.412] [INFO] system - { command: 'list' }
[2018-09-04 00:00:34.524] [INFO] system - { command: 'list' }
[2018-09-04 00:00:35.598] [INFO] system - { command: 'list' }
[2018-09-04 00:00:38.076] [INFO] system - { command: 'list' }
[2018-09-04 00:00:38.185] [INFO] system - { command: 'list' }
[2018-09-04 00:00:45.790] [INFO] system - { command: 'list' }
[2018-09-04 00:00:47.079] [INFO] system - { command: 'list' }
[2018-09-04 00:00:47.187] [INFO] system - { command: 'list' }
[2018-09-04 00:00:47.828] [INFO] system - { command: 'list' }
[2018-09-04 00:00:47.938] [INFO] system - { command: 'list' }
[2018-09-04 00:00:48.049] [INFO] system - { command: 'list' }
[2018-09-04 00:00:49.142] [INFO] system - { command: 'list' }
[2018-09-04 00:00:49.643] [INFO] system - { command: 'list' }
[2018-09-04 00:00:50.661] [INFO] system - { command: 'list' }
[2018-09-04 00:00:51.798] [INFO] system - { command: 'list' }
[2018-09-04 00:00:51.909] [INFO] system - { command: 'list' }
[2018-09-04 00:00:52.022] [INFO] system - { command: 'list' }
[2018-09-04 00:00:53.527] [INFO] system - { command: 'list' }
[2018-09-04 00:00:54.295] [INFO] system - { command: 'list' }
[2018-09-04 00:00:55.369] [INFO] system - { command: 'list' }
[2018-09-04 00:01:00.002] [INFO] system - Receive flow from shadowsocks: (libev)
{}
[2018-09-04 00:01:00.015] [INFO] system - { command: 'flow', options: { clear: true } }
[2018-09-04 00:01:01.531] [INFO] system - { command: 'list' }
[2018-09-04 00:01:03.569] [INFO] system - { command: 'list' }
[2018-09-04 00:01:05.222] [INFO] system - { command: 'list' }
[2018-09-04 00:01:07.774] [INFO] system - { command: 'list' }
[2018-09-04 00:01:07.884] [INFO] system - { command: 'list' }
[2018-09-04 00:01:09.431] [INFO] system - { command: 'list' }
[2018-09-04 00:01:10.304] [INFO] system - { command: 'list' }
[2018-09-04 00:01:10.414] [INFO] system - { command: 'list' }
[2018-09-04 00:01:10.968] [INFO] system - { command: 'list' }
[2018-09-04 00:01:11.963] [INFO] system - { command: 'list' }
[2018-09-04 00:01:13.439] [INFO] system - { command: 'list' }
[2018-09-04 00:01:13.549] [INFO] system - { command: 'list' }
[2018-09-04 00:01:14.121] [INFO] system - { command: 'list' }
[2018-09-04 00:01:14.229] [INFO] system - { command: 'list' }
[2018-09-04 00:01:21.317] [INFO] system - { command: 'list' }
[2018-09-04 00:01:22.513] [INFO] system - { command: 'list' }
[2018-09-04 00:01:23.538] [INFO] system - { command: 'list' }
[2018-09-04 00:01:23.646] [INFO] system - { command: 'list' }
[2018-09-04 00:01:25.591] [INFO] system - { command: 'list' }
[2018-09-04 00:01:25.700] [INFO] system - { command: 'list' }
[2018-09-04 00:01:26.280] [INFO] system - { command: 'list' }
[2018-09-04 00:01:26.856] [INFO] system - { command: 'list' }
[2018-09-04 00:01:26.965] [INFO] system - { command: 'list' }
[2018-09-04 00:01:28.447] [INFO] system - { command: 'list' }
[2018-09-04 00:01:29.086] [INFO] system - { command: 'list' }
[2018-09-04 00:01:29.199] [INFO] system - { command: 'list' }
[2018-09-04 00:01:31.496] [INFO] system - { command: 'list' }
[2018-09-04 00:01:35.202] [INFO] system - { command: 'list' }
[2018-09-04 00:01:37.904] [INFO] system - { command: 'list' }
[2018-09-04 00:01:40.349] [INFO] system - { command: 'list' }
[2018-09-04 00:01:41.482] [INFO] system - { command: 'list' }
[2018-09-04 00:01:45.426] [INFO] system - { command: 'list' }
[2018-09-04 00:01:47.386] [INFO] system - { command: 'list' }
[2018-09-04 00:01:47.941] [INFO] system - { command: 'list' }
[2018-09-04 00:01:48.050] [INFO] system - { command: 'list' }
[2018-09-04 00:01:48.160] [INFO] system - { command: 'list' }
[2018-09-04 00:01:48.731] [INFO] system - { command: 'list' }
[2018-09-04 00:01:48.842] [INFO] system - { command: 'list' }
[2018-09-04 00:01:48.952] [INFO] system - { command: 'list' }
[2018-09-04 00:01:49.061] [INFO] system - { command: 'list' }
[2018-09-04 00:01:54.047] [INFO] system - { command: 'list' }
[2018-09-04 00:01:56.297] [INFO] system - { command: 'list' }
[2018-09-04 00:01:56.406] [INFO] system - { command: 'list' }
[2018-09-04 00:01:56.831] [INFO] system - { command: 'list' }
[2018-09-04 00:01:59.813] [INFO] system - { command: 'list' }
[2018-09-04 00:02:00.002] [INFO] system - Receive flow from shadowsocks: (libev)
{}
[2018-09-04 00:02:00.021] [INFO] system - { command: 'flow', options: { clear: true } }
[2018-09-04 00:02:00.023] [INFO] system - { command: 'flow', options: { clear: true } }
[2018-09-04 00:02:00.400] [INFO] system - { command: 'list' }
[2018-09-04 00:02:00.971] [INFO] system - { command: 'list' }
[2018-09-04 00:02:01.082] [INFO] system - { command: 'list' }
[2018-09-04 00:02:01.193] [INFO] system - { command: 'list' }
[2018-09-04 00:02:02.689] [INFO] system - { command: 'list' }
[2018-09-04 00:02:02.801] [INFO] system - { command: 'list' }
[2018-09-04 00:02:12.256] [INFO] system - { command: 'list' }
[2018-09-04 00:02:12.367] [INFO] system - { command: 'list' }
[2018-09-04 00:02:13.102] [INFO] system - { command: 'list' }
[2018-09-04 00:02:14.059] [INFO] system - { command: 'list' }
```

**Comment by Yzi** [comment]
I also have the same problem.

**Comment by lhuang001** [comment]
系统：ubuntu16.04
ssmgr版本：0.26.2
vps：vultr
安装后也遇到磁盘高频写入的问题，且删除ssmgr后该问题消失。

**Comment by shminer** [comment]
Total DISK READ :       0.00 B/s | Total DISK WRITE :     759.73 K/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:       2.32 M/s
   PID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
   335 be/3 root        0.00 B/s    0.00 B/s  0.00 %  3.30 % [jbd2/nvme0n1p4-]
 58095 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.52 % [kworker/u256:0]
  2080 be/4 root        0.00 B/s  552.53 K/s  0.00 %  0.20 % node /usr/bin/ssmgr
  2096 be/4 root        0.00 B/s  207.20 K/s  0.00 %  0.09 % node /usr/bin/ssmgr


The same issues with high cpu iowait

**Comment by cokebar** [comment]
@codgician 你说的方法仅仅缓解了日志输出过快的问题，然而我这个issue里面已经把log4js关了，也就是不输出日志。这个问题里面是过于频繁的写数据库

**Comment by luvletter1205** [comment]
在0.30是启用了Redis做缓存，文档中是还没来得及添加如何配置Redis的教程吗？

**Comment by ken-gor** [comment]
https://shadowsocks.github.io/shadowsocks-manager/#/config
