### ISSUE TITLE
请求支付宝网关时发生错误

### ISSUE THREAD

**Issue by llong0625** [shadowsocks/shadowsocks-manager#467]
### What version of shadowsocks-manager are you using?
lastest

### What operating system are you using?
centos 7.5 x64

### What version of Node.js are you using?
v8.11.3

### What did you do?
续费生成支付二维码 支付扫码付款 

### What did you expect to see?
付款成功 并成功续时

### What did you see instead?
支付宝扫码 生成 信息 为 invalid qrcode
查看webgui.yml-out.log 错误信息为

[31m[2018-10-01 13:45:04.876] [ERROR] system - [39mUnhandled Rejection at: Promise Promise {
  <rejected> { message: '请求支付宝网关时发生错误',
  info: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at args.(anonymous function) (/usr/local/node/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' } } } reason: { message: '请求支付宝网关时发生错误',
  info: { Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at args.(anonymous function) (/usr/local/node/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9) code: 'ECONNRESET' } }

PS：生成付费二维码时 请求生成的qrcode 为null
{"orderId":"20181001132114941567","qrCode":null}
支付宝开发者中心API调用后台 显示调用失败
猜测是因为支付宝生成的二维码问题导致 

### What is your config in detail (with all sensitive info masked)?
web.yml 配置
type: m
empty: false

manager:
    address: ************:4001
    password: '123456'

plugins:
    flowSaver:
        use: true
    group:
        use: true
    user:
        use: true
    account:
        use: true
        pay:
            hour:
                price: 0.05
                flow: 500000000
            day:
                price: 0.5
                flow: 7000000000
            week:
                price: 3
                flow: 50000000000
            month:
                price: 10
                flow: 200000000000
            season:
                price: 30
                flow: 200000000000
            year:
                price: 120
                flow: 200000000000
    email:
        use: true
        type: 'smtp'
        username: '*****'
        password: '******'
        host: 'smtp.gmail.com'
    webgui:
        use: true
        host: '0.0.0.0'
        port: '80'
        site: 'http://***********'
    alipay:
        use: true
        appid: 2018093061530877
        notifyUrl: ''
        merchantPrivateKey: 'MIIEowIBAAKCAQEAo***********************Fj'
        alipayPublicKey: '**************eAQAB'
        gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'

**Comment by llong0625** [comment]
解决了 是因为没签约当面付的问题(拍脸表情)
