### ISSUE TITLE
--manager-address 模式无法启动

### ISSUE THREAD

**Issue by godsplans** [shadowsocks/shadowsocks-manager#47]
运行后会报错：```
root@xcc:~# ssserver --manager-address 127.0.0.1:6001 -c /root/ss.json
INFO: loading config from /root/ss.json
2016-08-28 03:50:40 WARNING  warning: server set to listen on 127.0.0.1:8388, are you sure?
2016-08-28 03:50:40 WARNING  warning: your timeout 60 seems too short
2016-08-28 03:50:40 INFO     loading libcrypto from libcrypto.so.1.0.0
2016-08-28 03:50:40 INFO     entering manager mode
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8389
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8388
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8387
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8386
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8385
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8384
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8383
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8382
2016-08-28 03:50:40 INFO     adding server at 127.0.0.1:8381
^CTraceback (most recent call last):
  File "/usr/local/bin/ssserver", line 9, in <module>
    load_entry_point('shadowsocks==2.9.0', 'console_scripts', 'ssserver')()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.9.0-py2.7.egg/shadowsocks/server.py", line 54, in main
    manager.run(config)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.9.0-py2.7.egg/shadowsocks/manager.py", line 194, in run
    Manager(config).run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.9.0-py2.7.egg/shadowsocks/manager.py", line 190, in run
    self._loop.run()
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.9.0-py2.7.egg/shadowsocks/eventloop.py", line 197, in run
    events = self.poll(TIMEOUT_PRECISION)
  File "/usr/local/lib/python2.7/dist-packages/shadowsocks-2.9.0-py2.7.egg/shadowsocks/eventloop.py", line 166, in poll
    events = self._impl.poll(timeout)
KeyboardInterrupt
```

**Comment by godsplans** [comment]
嗯已经好了，就这样就可以了，因为没加-d start参数，我以为还要显示started才可以。。
担现在还有个问题，端口密码可以添加，但是流量监控似乎没用啊

**Comment by glasswm** [comment]
server/controllers/shadowsocks.js  line:81里面有获取流量的代码，是根据ping命令后的返回值取得的。
但我测了一下，服务器好像ping后没有返回值。

环境是：ubuntu 14.04 LTS + pip install shadowsocks(version 2.8.2)

**Comment by glasswm** [comment]
又测了下自己的两个vps，虽然ping都是unkown command，但是digitalocean的vps能返回流量数据，而某不知名vps没有返回。
经测试与防火墙无关，暂无法定位原因，猜测是否与vps虚拟化架构相关。

**Comment by gyteng** [comment]
@glasswm 流量数据是才用udp协议传输的，请检查一下防火墙是不是禁用了udp协议

**Comment by glasswm** [comment]
@gyteng 没禁的，add remove命令都能正常执行

**Comment by gyteng** [comment]
@glasswm 这个我也不清楚了，我自己用的digitalocean和vultr都很正常，
或许你可以试试换一个版本的shadowsocks

**Comment by godsplans** [comment]
@gyteng 我的也是vultr，debian7，shadowsocks版本是2.9.0，网页添加端口密码后台都能看到提示，就是流量监控还是0B，还有怎么查看防火墙是否禁用了udp

**Comment by glasswm** [comment]
恩，这个问题应该是shadowsocks的，post到那边应该更合适：）

**Comment by godsplans** [comment]
@glasswm shadowsocks python版的怎么没有-u参数了

**Comment by godsplans** [comment]
卧槽居然好了，我只是重启了下manager，然后流量就奇迹般的开始增加了。。
