### ISSUE TITLE
启动shadowsocks-manager的时候显示/usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:3

### ISSUE THREAD

**Issue by jarny-auyang** [shadowsocks/shadowsocks-manager#479]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
version 2

### What operating system are you using?
Ubuntu 16.04.4 LTS

### What version of Node.js are you using?
v6.14.4

### What did you see instead?
启动shadowsocks-manager的时候显示
[2018-10-18 23:07:20.879] [INFO] system - System start.
[2018-10-18 23:07:21.283] [ERROR] system - Caught exception:
[2018-10-18 23:07:21.285] [ERROR] system - /usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:3
const init = async () => {
                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/server.js:28:44)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

### What is your config in detail (with all sensitive info masked)?
 ss.yml 配置：

type: s

shadowsocks:
  address: 127.0.0.1:6001
  # 这里的地址和端口需要跟上一步的 --manager-address 参数保持一致，连接上述 udp 端口
manager:
  address: 0.0.0.0:4001
  # 这个 address 参数会让程序监听一个 tcp 端口，用于接收 webgui 发送过来的控制命令
  password: '123456'
db: 'ss.sqlite'
---------------------------------------------------------------------

webgui.yml配置：

---------------------------------------------------------------------
type: m
 
manager:
  address: 47.75.88.121:4001
  # 这里换成manager所在的服务器的ip
  password: '123456'
  # 这部分的端口和密码需要跟上一步 manager 参数里的保持一致，以连接 type s 部分监听的 tcp 端口
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    type: 'smtp'
    username: '马赛克'
    password: '马赛克'
    host: '马赛克'
    # 这部分的邮箱和密码是用于发送注册验证邮件，重置密码邮件
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://47.75.88.121'
    # cdn: 'http://xxx.com' # 静态资源cdn地址，可省略
    # icon: 'icon.png' # 自定义首页图标，默认路径在 ~/.ssmgr 可省略
    # googleAnalytics: 'UA-xxxxxxxx-x' # Google Analytics ID，可省略
    # gcmSenderId: '456102641793' # gcmSenderId 、gcmAPIKey 这两个是Chrome推送用的
    # gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  #webgui_telegram:
    # telegram 机器人的配置，可省略
    #use: true
    #token: '191374681:AAw6oaVPR4nnY7T4CtW78QX-Xy2Q5WD3wmZ'
  #alipay:
    # 如果不使用支付宝，这段可以去掉
   # use: true
    #appid: 2015012108272442
    #notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    #merchantPrivateKey: 'xxxxxxxxxxxx'
    #alipayPublicKey: 'xxxxxxxxxxx'
    #gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  #paypal:
    # 如果不使用paypal，这段可以去掉
    #use: true
    #mode: 'live' # sandbox or live
    #client_id: 'At9xcGd1t5L6OrICKNnp2g9'
    #client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'
 
db: 'webgui.sqlite'

**Comment by gyteng** [comment]
用 node 8

**Comment by jarny-auyang** [comment]
> 用 node 8
可以了， 谢谢。

问一下有没有什么办法可以限制同一端口多个用户同时登录？
