### ISSUE TITLE
使用mysql数据库，注册login后报错

### ISSUE THREAD

**Issue by snakewqq** [shadowsocks/shadowsocks-manager#480]
[root@Ubuntu_18_SSR2 17:14 ~]$ docker logs -f ssmgr-m
/usr/lib/node_modules/shadowsocks-manager/
[2018-10-20 17:15:05.430] [INFO] system - System start.

{ Error: ER_WRONG_FIELD_WITH_GROUP: Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ssmgr.account_plugin.port' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    at Query.Sequence._packetToError (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
    --------------------
    at Protocol._enqueue (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:200:25)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:152:18
    at Promise._execute (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL._query (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:146:12)
    at Client_MySQL.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:197:17)
    at Runner.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/runner.js:146:36)
    at Runner.tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/method.js:15:34)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/runner.js:65:21
    at tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise_array.js:144:14)
  code: 'ER_WRONG_FIELD_WITH_GROUP',
  errno: 1055,
  sqlMessage: 'Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column \'ssmgr.account_plugin.port\' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by',
  sqlState: '42000',
  index: 0,
  sql: 'select sum(`saveFlow`.`flow`) as `sumFlow`, `user`.`id` as `userId`, `user`.`username` as `email`, `account_plugin`.`port` as `port`, `account_plugin`.`id` as `accountId` from `saveFlow` left join `account_plugin` on `account_plugin`.`id` = `saveFlow`.`accountId` inner join `user` on `account_plugin`.`userId` = `user`.`id` where `saveFlow`.`time` between 1539964800000 and 1540026973206 group by `user`.`id` order by `sumFlow` desc limit 5' }
[2018-10-20 17:16:13.226] [ERROR] express - [undefined] GET 403 56ms /api/admin/flow/top

**Comment by snakewqq** [comment]
sql_mode = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'

网上找到原因 是 MySQL5.7.5 版本以后默认开启 only_full_group_by 模式
user.username 带 group 导致出问题

简单解决办法是在MySQL配置文件里面去掉

在配置文件my.cnf中关闭sql_mode=ONLY_FULL_GROUP_BY.。msqyl的默认配置是sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION。可以把ONLY_FULL_GROUP_BY去掉，也可以去掉所有选项设置成sql_mode=，如果你确信其他选项不会造成影响的话。

#124
