### ISSUE TITLE
ssmgr -c ~/ssmgr/ss.yml 运行错误提示

### ISSUE THREAD

**Issue by caztg** [shadowsocks/shadowsocks-manager#500]
[2018-11-07T04:48:43.642] [ERROR] system - Caught exception:
[2018-11-07T04:48:43.644] [ERROR] system - /usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:3
const init = async () => {
                   ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/server.js:23:44)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

**Comment by llc1123** [comment]
仅支持 node 8.x 10.x

**Comment by smallprogram** [comment]
我通过配置文档一步一步的做，最后也是显示.returning() is not supported by sqlite3 and will not have any effect.不明所以

**Comment by caztg** [comment]
> 我通过配置文档一步一步的做，最后也是显示.returning() is not supported by sqlite3 and will not have any effect.不明所以

这个好像不重要，可以继续使用

**Comment by jianjustin** [comment]
这个问题可以不处理吗？
