### ISSUE TITLE
Everything is fine, except that new account won't work. WHY???

### ISSUE THREAD

**Issue by imjcker** [shadowsocks/shadowsocks-manager#509]
### What version of shadowsocks-manager are you using?
newest version from GitHub

### What operating system are you using?
CentOS 7

### What version of Node.js are you using?
v8.13.0

### What did you do?
just wanna deploy this wegui, so I did exactly what the tutorial told me to do.

### What did you expect to see?
I just want it actually work

### What did you see instead?
some error log as follow:
```shell
tail -f nohup.out 
    at Socket.client.on.err (/usr/lib/node_modules/shadowsocks-manager/services/manager.js:88:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
[2018-11-26T21:23:57.796] [ERROR] express - [undefined] GET 401 14ms /api/user/server
[2018-11-26T21:23:57.813] [ERROR] express - [undefined] GET 401 26ms /api/user/order
[2018-11-26T21:23:57.821] [ERROR] express - [undefined] GET 401 31ms /api/user/account
[2018-11-26T21:23:57.831] [ERROR] express - [undefined] GET 401 41ms /api/user/notice

```

### What is your config in detail (with all sensitive info masked)?
just like the tutorial except the port.

**Comment by imjcker** [comment]
Anything to say?
