### ISSUE TITLE
Error: Cannot find module './lib/toDate'

### ISSUE THREAD

**Issue by edwardfr** [shadowsocks/shadowsocks-manager#52]
请问这个报错是什么原因 CentOS7
[root@localhost shadowsocks-manager]# node server.js
module.js:327
    throw err;
    ^

Error: Cannot find module './lib/toDate'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/shadowsocks-manager/node_modules/express-validator/node_modules/validator/index.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by gyteng** [comment]
没有遇到过，建议采用非root账户试试

2016-09-02 15:38 GMT+08:00 edwardfr <notifications@github.com>:
