### ISSUE TITLE
npm 安装报错(sqlite3)

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/shadowsocks-manager#538]
### What version of shadowsocks-manager are you using?
v0.30

### What operating system are you using?
Ubuntu 18.04 on WSL / Ubuntu 16.04 on KVM

### What version of Node.js are you using?
v10.15.0

### What did you do?
sudo npm i shadowsocks-manager -g

### What did you expect to see?
installed successfully

### What did you see instead?
Error happend when installing sqlite3 module
```
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
/usr/bin/ssmgr -> /usr/lib/node_modules/shadowsocks-manager/bin/ssmgr

> sqlite3@4.0.6 install /usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.0.6 and node@10.15.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding'
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/cokebar/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/.node-gyp'
gyp ERR! System Linux 4.4.0-17763-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.4.0-17763-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/shadowsocks-manager/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/lib/node_modules/shadowsocks-manager/node_modules/sqlite3/lib/binding/node-v64-linux-x64 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cokebar/.npm/_logs/2019-01-28T06_41_36_289Z-debug.log
```

**Comment by hsnpersia** [comment]
Use sudo npm i -g shadowsocks-manager --unsafe-perm

**Comment by cokebar** [comment]
solved. thanks
