### ISSUE TITLE
startup problem

### ISSUE THREAD

**Issue by Arhimad** [shadowsocks/shadowsocks-manager#541]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?

/usr/lib
└─┬ shadowsocks-manager@0.30.16

### What operating system are you using?
Ubuntu 16.04 x64

### What version of Node.js are you using?
~# node -v
v6.16.0

### What did you do?

_when i run:_

**:~# ssmgr -x -- -c ss.yml --debug**
/usr/lib/node_modules/shadowsocks-manager/
/usr/lib/node_modules/shadowsocks-manager/server.js:21
const startWorker = async () => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/bin/ssmgr:8:1)
**:~# ssmgr -V**
/usr/lib/node_modules/shadowsocks-manager/
/usr/lib/node_modules/shadowsocks-manager/server.js:21
const startWorker = async () => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/bin/ssmgr:8:1)

**:~# ssmgr -x -- -c webgui.yml --debug**
/usr/lib/node_modules/shadowsocks-manager/
/usr/lib/node_modules/shadowsocks-manager/server.js:21
const startWorker = async () => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/bin/ssmgr:8:1)

### What is your config in detail (with all sensitive info masked)?

**File: /root/.ssmgr/ss.yml**

type: s
empty: false
shadowsocks:
  address: 127.0.0.1:6001
  #portRange: 50000-51000,55000,55002
manager:
  address: 0.0.0.0:6002
  password: '********'
db: 'ss.sqlite'

**File: /root/.ssmgr/webgui.yml**                                          

type: m
empty: false

manager:
    address: 127.0.0.1:6002
    password: '******'

plugins:
    flowSaver:
        use: true
    user:
        use: true
    account:
        use: true
        pay:
            hour:
                price: 1
                flow: 500000000
            day:
                price: 5
                flow: 7000000000
            week:
                price: 10
                flow: 50000000000
            month:
                price: 20
                flow: 200000000000
            season:
                price: 70
                flow: 200000000000
            year:
                price: 250
                flow: 200000000000
    giftcard:
        use: true
    group:
        use: true
    macAccount:
        use: true
    email:
        use: true
        username: '*****'
        password: '******'
        host: 'smtp.******'
        port: 465
    webgui:
        use: true
        host: '0.0.0.0'
        port: '80'
        site: 'http://********'
        gcmSenderId: '4**3'
        gcmAPIKey: '**'

db: 'webgui.sqlite'

**Comment by 4553733** [comment]
The system version I am currently using: Centos 6 x64

I had a problem during the installation and use, and finally found that it could not start normally.

I used the installation method given online.

**installation:**
`git clone https://github.com/gyteng/shadowsocks-manager-tiny.git
curl -sL https://rpm.nodesource.com/setup_6.x | bash -
yum install -y nodejs`

**start up:**
`yum install -y screen
ssserver -m aes-256-cfb -p 1001 -k aqwesdfas --manager-address 127.0.0.1:6001 -d start
cd shadowsocks-manager-tiny
screen -dmS ssmgr node index.js 127.0.0.1:6001 0.0.0.0:4001 yourpasswordum install -y screen
ssserver -m aes-256-cfb -p 1001 -k aqwesdfas --manager-address 127.0.0.1:6001 -d start
cd shadowsocks-manager-tiny
screen -dmS ssmgr node index.js 127.0.0.1:6001 0.0.0.0:4001 yourpassword`


**But in the end, I found an error:**
`[root@vultr shadowsocks-manager-tiny]# node index.js 127.0.0.1:6001 0.0.0.0:4001 yourpassword
/root/shadowsocks-manager-tiny/shadowsocks.js:44
setInterval(async () => {
                  ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/shadowsocks-manager-tiny/index.js:9:1)
[root@vultr shadowsocks-manager-tiny]# `

**Where is the specific problem? Thank you**

**Comment by Arhimad** [comment]
from the instructions said:

_Dependencies
Node.js 10.*
Redis_

use:
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
and installing: 
yum install -y redis-server

**but your problem is decided when installing:**

npm i -g sqlite3 --unsafe-perm

**Comment by 4553733** [comment]
The tiny version used before, now changed back to the original version, the problem has been solved, thank the author for answering.
 
@Arhimad
