### ISSUE TITLE
Redis ERROR

### ISSUE THREAD

**Issue by caztg** [shadowsocks/shadowsocks-manager#559]
[ERROR] system - Unhandled Rejection at: Promise {} reason: MaxRetriesPerRequestError: Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.
    at Socket.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/ioredis/built/redis/event_handler.js:95:37)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:600:12)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)

**Comment by caztg** [comment]
没办法，安装了个redis， 问题虽然解决了，但好像比较麻烦，我看看怎么关闭

**Comment by HelloGit100** [comment]
> 没办法，安装了个redis， 问题虽然解决了，但好像比较麻烦，我看看怎么关闭

我安装了redis，也给redis设置了密码，但是还是出现"[ioredis] Unhandled error event"问题，点最下面Comment按钮左侧的Close关闭

**Comment by myfingerhurt** [comment]
if this happens:
`Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379`
run this:
`sudo apt install redis`
