### ISSUE TITLE
[Error]: SQLITE_ERROR: no such table: user errno: 1, code: 'SQLITE_ERROR' 

### ISSUE THREAD

**Issue by fttomas** [shadowsocks/shadowsocks-manager#588]
### What version of shadowsocks-manager are you using?
shadowsocks-manager 0.32.7
shadowsocks-libev 3.1.3

### What operating system are you using?
ubuntu 18.04

### What version of Node.js are you using?
v8.10.0

### What did you do?
**shadowsocks + manager + webgui**

**Start server:**
systemctl start shadowsocks-libev.service
systemctl status shadowsocks-libev.service
```
● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-05-25 23:31:48 CEST; 32min ago
     Docs: man:shadowsocks-libev(8)
 Main PID: 19175 (ss-server)
    Tasks: 1 (limit: 2299)
   CGroup: /system.slice/shadowsocks-libev.service
           └─19175 /usr/bin/ss-server -c /etc/shadowsocks-libev/config.json -u
```

cat /etc/shadowsocks-libev/config.json
```
{
    "server":"127.0.0.1",
    "server_port":4000,
    "local_port":1080,
    "password":"123456",
    "timeout":10,
    "method":"aes-256-cfb",
    "fast_open":true,
    "workers":1,
    "mode":"tcp_and_udp"
}
```
**Start manager:**
root@SHS:~/.ssmgr# ssmgr --debug
```
/usr/local/lib/node_modules/shadowsocks-manager/
[2019-05-26T00:09:09.439] [INFO] system - System start[20053].
/usr/local/lib/node_modules/shadowsocks-manager/
[2019-05-26T00:09:10.168] [INFO] system - System start[20059].
[2019-05-26T00:09:10.170] [INFO] system - Worker [20059] started
[2019-05-26T00:09:10.231] [INFO] system - Config file path:  /home/1/.ssmgr/default.yml
[2019-05-26T00:09:10.536] [INFO] system - server listen on 127.0.0.1:4001
```
root@SHS:~/.ssmgr# cat /home/1/.ssmgr/default.yml
```
type: s

shadowsocks:
  address: '127.0.0.1:4000'

manager:
  address: '127.0.0.1:4001'
  password: '123456'

  #db: 'db.sqlite'

db:
   host: '127.0.0.1'
   user: 'shadowsocks'
   password: 'shadowsocks1'
   database: 'smanager'
```

cat /home/1/.ssmgr/webgui.yml
```
type: m
manager:
  address: 127.0.0.1:4001
  password: '123456'
plugins:
 webgui:
    use: true
    host: '127.0.0.1'
    port: '8080'
    site: 'http://XXX.XXX.XXX.XXX'
db: 'webgui.sqlite'
    #db:
    #host: '127.0.0.1'
    #user: 'shadowsocks'
    #password: 'shadowsocks1'
    #database: 'webqui'
```
**And fail webgui:**
ssmgr -c /home/1/.ssmgr/webgui.yml --debug
```
/usr/local/lib/node_modules/shadowsocks-manager/
[2019-05-26T00:19:03.473] [INFO] system - System start[20382].
/usr/local/lib/node_modules/shadowsocks-manager/
[2019-05-26T00:19:04.148] [INFO] system - System start[20388].
[2019-05-26T00:19:04.149] [INFO] system - Worker [20388] started
[2019-05-26T00:19:04.224] [INFO] system - Config file path:  /home/1/.ssmgr/webgui.yml
[2019-05-26T00:19:04.475] [INFO] system - Load plugin db: [ webgui ]
[2019-05-26T00:19:04.477] [INFO] system - Load plugin db: [ webgui/db/notice.js ]
[2019-05-26T00:19:04.478] [INFO] system - Load plugin db: [ webgui/db/push.js ]
[2019-05-26T00:19:04.479] [INFO] system - Load plugin db: [ webgui/db/setting.js ]
[2019-05-26T00:19:04.487] [INFO] system - Load plugin dependence: [ webgui ]
[2019-05-26T00:19:04.488] [INFO] system - Load plugin db: [ webgui_ref ]
[2019-05-26T00:19:04.488] [INFO] system - Load plugin db: [ webgui_ref/db/webgui_ref.js ]
[2019-05-26T00:19:04.489] [INFO] system - Load plugin db: [ webgui_ref/db/webgui_ref_code.js ]
[2019-05-26T00:19:04.489] [INFO] system - Load plugin db: [ webgui_ref/db/webgui_ref_time.js ]
[2019-05-26T00:19:04.491] [INFO] system - Load plugin db: [ group ]
[2019-05-26T00:19:04.492] [INFO] system - Load plugin db: [ group/db/group.js ]
[2019-05-26T00:19:04.492] [INFO] system - Load plugin db: [ group/db/noticeGroup.js ]
[2019-05-26T00:19:04.520] [INFO] system - Load plugin db: [ macAccount ]
[2019-05-26T00:19:04.521] [INFO] system - Load plugin db: [ macAccount/db/macAccount.js ]
[2019-05-26T00:19:04.522] [INFO] system - Load plugin db: [ webgui_order ]
[2019-05-26T00:19:04.522] [INFO] system - Load plugin db: [ webgui_order/db/webgui_flow_pack.js ]
[2019-05-26T00:19:04.523] [INFO] system - Load plugin db: [ webgui_order/db/webgui_order.js ]
[2019-05-26T00:19:04.529] [INFO] system - Load plugin db: [ account_checker ]
[2019-05-26T00:19:04.530] [INFO] system - Load plugin: [ webgui ]
[2019-05-26T00:19:04.922] [ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'type' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/email/index.js:13:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/home.js:10:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/route.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32) } reason: TypeError: Cannot read property 'type' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/email/index.js:13:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/home.js:10:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/route.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
[2019-05-26T00:19:04.964] [INFO] webgui - server start at 127.0.0.1:8080
**[2019-05-26T00:19:04.973] [ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> { Error: SQLITE_ERROR: no such table: user errno: 1, code: 'SQLITE_ERROR' } } reason: { Error: SQLITE_ERROR: no such table: user errno: 1, code: 'SQLITE_ERROR' }**
```

When executing the last command an error is issued, what am I doing wrong?

**Comment by gyteng** [comment]
redis

**Comment by fttomas** [comment]
Redis in installed:
```
```
root@SHS:~# apt show redis
Package: redis
Version: 5:4.0.9-1ubuntu0.1
Priority: optional
Section: universe/database
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Chris Lamb <lamby@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 71,7 kB
Depends: redis-server (<< 5:4.0.9-1ubuntu0.1.1~), redis-server (>= 5:4.0.9-1ubuntu0.1)
Homepage: http://redis.io/
Download-Size: 3 088 B
APT-Manual-Installed: yes
```
server start:
root@SHS:~# ssmgr -c /home/1/.ssmgr/webgui.yml --debug
/usr/local/lib/node_modules/shadowsocks-manager/
[2019-05-27T08:16:10.766] [INFO] system - System start[2316].
/usr/local/lib/node_modules/shadowsocks-manager/
[2019-05-27T08:16:11.539] [INFO] system - System start[2322].
[2019-05-27T08:16:11.542] [INFO] system - Worker [2322] started
[2019-05-27T08:16:11.617] [INFO] system - Config file path:  /home/1/.ssmgr/webgui.yml
[2019-05-27T08:16:11.923] [INFO] system - Load plugin db: [ webgui ]
[2019-05-27T08:16:11.925] [INFO] system - Load plugin db: [ webgui/db/notice.js ]
[2019-05-27T08:16:11.926] [INFO] system - Load plugin db: [ webgui/db/push.js ]
[2019-05-27T08:16:11.927] [INFO] system - Load plugin db: [ webgui/db/setting.js ]
[2019-05-27T08:16:11.938] [INFO] system - Load plugin dependence: [ webgui ]
[2019-05-27T08:16:11.939] [INFO] system - Load plugin db: [ webgui_ref ]
[2019-05-27T08:16:11.939] [INFO] system - Load plugin db: [ webgui_ref/db/webgui_ref.js ]
[2019-05-27T08:16:11.940] [INFO] system - Load plugin db: [ webgui_ref/db/webgui_ref_code.js ]
[2019-05-27T08:16:11.941] [INFO] system - Load plugin db: [ webgui_ref/db/webgui_ref_time.js ]
[2019-05-27T08:16:11.944] [INFO] system - Load plugin db: [ group ]
[2019-05-27T08:16:11.945] [INFO] system - Load plugin db: [ group/db/group.js ]
[2019-05-27T08:16:11.946] [INFO] system - Load plugin db: [ group/db/noticeGroup.js ]
[2019-05-27T08:16:11.984] [INFO] system - Load plugin db: [ macAccount ]
[2019-05-27T08:16:11.985] [INFO] system - Load plugin db: [ macAccount/db/macAccount.js ]
[2019-05-27T08:16:11.987] [INFO] system - Load plugin db: [ webgui_order ]
[2019-05-27T08:16:11.988] [INFO] system - Load plugin db: [ webgui_order/db/webgui_flow_pack.js ]
[2019-05-27T08:16:11.988] [INFO] system - Load plugin db: [ webgui_order/db/webgui_order.js ]
[2019-05-27T08:16:11.998] [INFO] system - Load plugin db: [ account_checker ]
[2019-05-27T08:16:11.999] [INFO] system - Load plugin: [ webgui ]
[2019-05-27T08:16:12.500] [ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'type' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/email/index.js:13:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/home.js:10:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/route.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32) } reason: TypeError: Cannot read property 'type' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/email/index.js:13:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/home.js:10:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/init/utils.js:4:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/plugins/webgui/server/route.js:6:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
[2019-05-27T08:16:12.550] [INFO] webgui - server start at 127.0.0.1:8080
[2019-05-27T08:16:12.560] [ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> { Error: SQLITE_ERROR: no such table: user errno: 1, code: 'SQLITE_ERROR' } } reason: { Error: SQLITE_ERROR: no such table: user errno: 1, code: 'SQLITE_ERROR' }
```

**Comment by fttomas** [comment]
http://ххх.ххх.ххх.ххх:8080/
`Cannot GET /`

logs:
`│> [2019-05-27T09:31:15.032] [ERROR] express - [ххх.ххх.ххх.ххх:8080] [undefined] GET 404 16ms /`
