### ISSUE TITLE
mysql 8.0 support

### ISSUE THREAD

**Issue by solace20** [shadowsocks/shadowsocks-manager#663]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)
Unhandled Rejection at: Promise Promise {
  <rejected> Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
      at Handshake.Sequence._packetToError (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Handshake.ErrorPacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
      at Protocol._parsePacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
      --------------------
      at Protocol._enqueue (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at Protocol.handshake (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/protocol/Protocol.js:51:23)
      at Connection.connect (/usr/lib/node_modules/shadowsocks-manager/node_modules/mysql/lib/Connection.js:116:18)
      at /usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:69:18
      at Promise._execute (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/debuggability.js:384:9)
      at Promise._resolveFromExecutor (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:518:18)
      at new Promise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:103:10)
      at Client_MySQL.acquireRawConnection (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/dialects/mysql/index.js:64:12)
      at create (/usr/lib/node_modules/shadowsocks-manager/node_modules/knex/lib/client.js:290:39)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    code: 'ER_NOT_SUPPORTED_AUTH_MODE',
    errno: 1251,
    sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
    sqlState: '08004',

(PS, you can remove 3 lines above, including this one, before post your issue.)

**Comment by gyteng** [comment]
add `--default-authentication-plugin=mysql_native_password`
