### ISSUE TITLE
无法添加或修改服务器

### ISSUE THREAD

**Issue by a1711hw** [shadowsocks/shadowsocks-manager#684]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-manager are you using?
v0.37.4 and  v1.0.0

### What operating system are you using?
centos 7

### What version of Node.js are you using?
v12.9.1

### What did you do?
npm i -g shadowsocks-manager --unsafe-perm

在webgui 修改或添加服务器时，webgui日志报错（域名和IP地址已脱敏）：

[2022-10-31T00:18:44.134] [ERROR] system - timeout
Error: connect to ssmgr[s] timeout [***.*******.***:6001]
    at Socket.<anonymous> (/usr/local/node/lib/node_modules/shadowsocks-manager/services/manager.js:98:14)
    at Socket.emit (events.js:209:13)
    at Socket._onTimeout (net.js:434:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2022-10-31T00:18:44.151] [ERROR] express - [***.*******.***] [xx.xx.xx.xx] POST 403 10389ms /api/admin/server
[2022-10-31T00:18:46.099] [ERROR] system - { code: 2 }
[2022-10-31T00:18:46.100] [ERROR] account - Error: ssmgr[s] return an error code [***.*******.***:6001]
    at /usr/local/node/lib/node_modules/shadowsocks-manager/services/manager.js:81:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2022-10-31T00:18:46.560] [ERROR] system - { code: 2 }
[2022-10-31T00:18:46.560] [ERROR] account - Error: ssmgr[s] return an error code [***.*******.***:6001]
    at /usr/local/node/lib/node_modules/shadowsocks-manager/services/manager.js:81:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2022-10-31T00:18:47.276] [ERROR] system - { code: 2 }
[2022-10-31T00:18:47.276] [ERROR] account - Error: ssmgr[s] return an error code [***.*******.***:6001]
    at /usr/local/node/lib/node_modules/shadowsocks-manager/services/manager.js:81:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2022-10-31T00:18:47.733] [ERROR] system - { code: 2 }
[2022-10-31T00:18:47.733] [ERROR] account - Error: ssmgr[s] return an error code [***.*******.***:6001]
    at /usr/local/node/lib/node_modules/shadowsocks-manager/services/manager.js:81:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2022-10-31T00:18:49.337] [ERROR] system - Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at Socket.Writable.write (_stream_writable.js:299:5)
    at Socket.<anonymous> (/usr/local/node/lib/node_modules/shadowsocks-manager/services/manager.js:66:14)
    at Object.onceWrapper (events.js:297:20)
    at Socket.emit (events.js:214:15)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1042:10)
[2022-10-31T00:18:51.195] [ERROR] system - { code: 2 }

**Comment by a1711hw** [comment]
是server和 agent的时差问题
