### ISSUE TITLE
[ERROR] system - TypeError: Cannot read property 'empty' of undefined

### ISSUE THREAD

**Issue by zicjin** [shadowsocks/shadowsocks-manager#76]
```
root@ubuntu-512mb-sfo1-01:~/.ssmgr# ssmgr -t s -s 127.0.0.1:6001 -m 0.0.0.0:6002
/usr/lib/node_modules/shadowsocks-manager/
[2016-11-01 09:18:49.287] [INFO] system - System start.
[2016-11-01 09:18:49.482] [INFO] system - Config file path:  /root/.ssmgr/default.yml
[2016-11-01 09:18:49.493] [INFO] system - { Error: (unknown reason)
    at generateError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1074:7)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readBlockMapping (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1056:11)
    at composeNode (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1488:3)
    at loadDocuments (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1544:5)
    at load (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1561:19)
    at Object.safeLoad (/usr/lib/node_modules/shadowsocks-manager/node_modules/js-yaml/lib/js-yaml/loader.js:1579:10)
  name: 'YAMLException',
  reason: 'bad indentation of a mapping entry',
  mark:
   Mark {
     name: null,
     buffer: 'type: s\r\nempty: false\r\n\r\nshadowsocks:\r\n    address: 127.0.0.1:6001\r\n\r\nmanager:\r\n    address: 127.0.0.1:6002\r\n    password: \'123456\'\r\n\r\nplugins:\r\n    telegram:\r\n        use: false\r\n        token: \'\'\r\n    cli:\r\n        use: true\r\n    flowSaver:\r\n        use: false\r\n    email:\r\n        use: false\r\n        user: \'username\'\r\n        password: \'password\',\r\n        host: \'smtp.your-email.com\'\r\n\r\ndb: \'db.sqlite\'\r\n\r\n\u0000',
     position: 350,
     line: 21,
     column: 28 },
  message: 'bad indentation of a mapping entry at line 22, column 29:\n            password: \'password\',\n                                ^' }
[2016-11-01 09:18:49.506] [INFO] system - Config:
 undefined
[2016-11-01 09:18:49.836] [ERROR] system - TypeError: Cannot read property 'empty' of undefined
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/models/account.js:8:6)
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/shadowsocks-manager/models/account.js:3:191)
    at /usr/lib/node_modules/shadowsocks-manager/models/account.js:3:437
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/models/account.js:3:99)
    at Object.createTable (/usr/lib/node_modules/shadowsocks-manager/models/account.js:7:7)
    at /usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:11:37
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:3:191)
    at /usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:3:437
    at /usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:3:99
    at init (/usr/lib/node_modules/shadowsocks-manager/init/loadModels.js:5:7)
    at Object.<anonymous> (/usr/lib/node_modules/shadowsocks-manager/server.js:25:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
```

/root/.ssmgr/default.yml:
```
type: s
empty: false

shadowsocks:
    address: 127.0.0.1:6001

manager:
    address: 127.0.0.1:6002
    password: '123456'

plugins:
    telegram:
        use: false
        token: ''
    cli:
        use: true
    flowSaver:
        use: false
    email:
        use: false
        user: 'username'
        password: 'password',
        host: 'smtp.your-email.com'

db: 'db.sqlite'
```

**Comment by gyteng** [comment]
刚刚那个是配置文件格式错误的bug，已经修复，请删除~/.ssmgr/default.yml并更新到最新版本重试。

2016-11-01 17:21 GMT+08:00 zicjin <notifications@github.com>:
