### ISSUE TITLE
按照README配置好之后出错

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-manager#82]
错误信息：
```
Error: Failed to lookup view "index" in views directory "/usr/lib/node_modules/shadowsocks-manager/lib/plugins/freeAccount/views"
    at EventEmitter.render (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/response.js:960:7)
    at render (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/freeAccount/server/user.js:74:14)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:277:22
    at param (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:349:14)
    at param (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:271:10)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/express-session/index.js:473:7
    at tryCatcher (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:564:21)
```

访问 IP:80 端口提示：Internal Server Error

**Comment by gyteng** [comment]
请注明你的操作系统，node版本号等

2016年12月10日 17:41，"Xingyu Chen" <notifications@github.com>写道：

错误信息：

Error: Failed to lookup view "index" in views directory
"/usr/lib/node_modules/shadowsocks-manager/lib/plugins/freeAccount/views"
    at EventEmitter.render
(/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/application.js:579:17)
    at ServerResponse.render
(/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/response.js:960:7)
    at render (/usr/lib/node_modules/shadowsocks-manager/lib/plugins/freeAccount/server/user.js:74:14)
    at Layer.handle [as handle_request]
(/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch
(/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request]
(/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:277:22
    at param (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:349:14)
    at param (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params
(/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/lib/node_modules/shadowsocks-manager/node_modules/express/lib/router/index.js:271:10)
    at /usr/lib/node_modules/shadowsocks-manager/node_modules/express-session/index.js:473:7
    at tryCatcher
(/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0]
(/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise
(/usr/lib/node_modules/shadowsocks-manager/node_modules/bluebird/js/release/promise.js:564:21)

访问IP:80端口提示
Internal Server Error

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shadowsocks/shadowsocks-manager/issues/82>, or mute the
thread

**Comment by pexcn** [comment]
Ubuntu 14.04, Nodejs 6.9.2

**Comment by gyteng** [comment]
已经找到问题了，稍后修复，建议你可以暂时先采用 git clone 的方式安装已避免这个问题

2016年12月10日 17:57，"Xingyu Chen" <notifications@github.com>写道：

**Comment by pexcn** [comment]
原来是 bug 啊，一直是以为是我配置问题，谢谢了~

**Comment by pexcn** [comment]
我刚刚用 git clone 的方式试了，但是仍然存在这个错误。@gyteng

**Comment by pexcn** [comment]
更新到最新代码了，又试了一次，但是仍旧是这个错误

**Comment by gyteng** [comment]
@pexcn 你要把npm里的包更新
运行
`npm i -g shadowsocks-manager`更新到0.3.23版本

**Comment by pexcn** [comment]
好的，谢谢~
