### ISSUE TITLE
bower install angular crashed

### ISSUE THREAD

**Issue by deric0314** [shadowsocks/shadowsocks-manager#92]
运行bower install 显示需要选择版本 先行选择1.5.7网页有错误后又安装1.6.1.
但运行网页后仍有报错，网页字体图标都无法显示、布局混乱。请大神指教~  新年快乐^_^

web console show the message：
`angular.js:14328Error: transition superseded
    at v [as $get] (http://191.101.225.183:6003/libs/angular-ui-router/release/angular-ui-router.min.js:7:16122)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:44:486
    at d (http://191.101.225.183:6003/libs/angular/angular.min.js:42:92)
    at e (http://191.101.225.183:6003/libs/angular/angular.min.js:42:333)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:42:418)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:54:276
    at q (http://191.101.225.183:6003/libs/angular/angular.min.js:7:351)
    at Object.<anonymous> (http://191.101.225.183:6003/libs/angular/angular.min.js:54:243)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175) Possibly unhandled rejection: {}(anonymous function) @ angular.js:14328
angular.js:14328Error: transition prevented
    at v [as $get] (http://191.101.225.183:6003/libs/angular-ui-router/release/angular-ui-router.min.js:7:16169)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:44:486
    at d (http://191.101.225.183:6003/libs/angular/angular.min.js:42:92)
    at e (http://191.101.225.183:6003/libs/angular/angular.min.js:42:333)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:42:418)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:54:276
    at q (http://191.101.225.183:6003/libs/angular/angular.min.js:7:351)
    at Object.<anonymous> (http://191.101.225.183:6003/libs/angular/angular.min.js:54:243)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175) Possibly unhandled rejection: {}(anonymous function) @ angular.js:14328
angular.js:14328Error: transition aborted
    at v [as $get] (http://191.101.225.183:6003/libs/angular-ui-router/release/angular-ui-router.min.js:7:16215)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:44:486
    at d (http://191.101.225.183:6003/libs/angular/angular.min.js:42:92)
    at e (http://191.101.225.183:6003/libs/angular/angular.min.js:42:333)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:42:418)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:54:276
    at q (http://191.101.225.183:6003/libs/angular/angular.min.js:7:351)
    at Object.<anonymous> (http://191.101.225.183:6003/libs/angular/angular.min.js:54:243)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175) Possibly unhandled rejection: {}(anonymous function) @ angular.js:14328
angular.js:14328Error: transition failed
    at v [as $get] (http://191.101.225.183:6003/libs/angular-ui-router/release/angular-ui-router.min.js:7:16259)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:44:486
    at d (http://191.101.225.183:6003/libs/angular/angular.min.js:42:92)
    at e (http://191.101.225.183:6003/libs/angular/angular.min.js:42:333)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:42:418)
    at http://191.101.225.183:6003/libs/angular/angular.min.js:54:276
    at q (http://191.101.225.183:6003/libs/angular/angular.min.js:7:351)
    at Object.<anonymous> (http://191.101.225.183:6003/libs/angular/angular.min.js:54:243)
    at Object.invoke (http://191.101.225.183:6003/libs/angular/angular.min.js:43:175) Possibly unhandled rejection: {}(anonymous function) @ angular.js:14328
http://191.101.225.183:6003/libs/material-design-icons/iconfont/MaterialIcons-Regular.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)
http://191.101.225.183:6003/libs/material-design-icons/iconfont/MaterialIcons-Regular.woff Failed to load resource: the server responded with a status of 404 (Not Found)
http://191.101.225.183:6003/libs/material-design-icons/iconfont/MaterialIcons-Regular.ttf Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by gyteng** [comment]
把bower的文件夹删除再重新运行bower install

2017-01-29 17:19 GMT+08:00 deric0314 <notifications@github.com>:

**Comment by deric0314** [comment]
谢谢，好像是因为jquery没有导入的关系。不过还是有错，期待新版~
