### ISSUE TITLE
There is an error,,, I don't know why I just did it via the tutorial  [Unhandled Rejection]

### ISSUE THREAD

**Issue by shiqwang** [shadowsocks/shadowsocks-manager#95]
[2017-02-07 09:50:24.176] [ERROR] system - Unhandled Rejection at: Promise Promise {
  <rejected> [RangeError: Offset + length beyond buffer length] } reason: [RangeError: Offset + length beyond buffer length]
RangeError: Offset + length beyond buffer length
    at Socket.send (dgram.js:273:11)
    at /usr/local/lib/node_modules/shadowsocks-manager/lib/services/shadowsocks.js:104:12
    at next (native)
    at step (/usr/local/lib/node_modules/shadowsocks-manager/lib/services/shadowsocks.js:3:191)
    at /usr/local/lib/node_modules/shadowsocks-manager/lib/services/shadowsocks.js:3:437
    at /usr/local/lib/node_modules/shadowsocks-manager/lib/services/shadowsocks.js:3:99
    at startUp (/usr/local/lib/node_modules/shadowsocks-manager/lib/services/shadowsocks.js:115:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/shadowsocks-manager/lib/services/shadowsocks.js:155:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at global.appRequire.filePath (/usr/local/lib/node_modules/shadowsocks-manager/lib/init/utils.js:6:10)
    at shadowsocks (/usr/local/lib/node_modules/shadowsocks-manager/lib/init/loadServices.js:7:3)

**Comment by gyteng** [comment]
Please give more details, your node version, your config files and args
when you start the program.

2017-02-07 17:52 GMT+08:00 Shiqi <notifications@github.com>:

**Comment by shiqwang** [comment]
@gyteng Hey gyteng, Thank you, I fixed that problem. I changed my nodejs version to 6.9.5.I was so confused about that document.
But, the new problem is coming, here is the log ...

[2017-02-08 03:01:16.848] [INFO] system - Receive flow from shadowsocks: (libev)
{}

I don't know what to do next, is that meaning everything goes well?

And, by the way, how can I manager user and control the traffice. Is there any instruction about that? 

As a super newbie sorry for the basic questions.
Anyway, thank you for your attention.

**Comment by gyteng** [comment]
you have to run another ssmgr to mange it, like that:

```
shadowsocks <--> ssmgr --type s <--> ssmgr --type m
```
if you have serval servers, you can start ssmgr with `--type s` in every
server, and manage all of them by ssmgr --type m

2017-02-08 11:31 GMT+08:00 Shiqi <notifications@github.com>:

**Comment by shiqwang** [comment]
I ran shadowsocks-libev as 
```ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001```
And I ran ```ssmgr -t s```, it outputted the information of that config.
Then I ran ```ssmgr -t m```, it also outputted, and a few seconds later, it exited automatically.

Even it didn't exit, what I should to do next? Is there some command or website I can manager the users and control traffic?

OMG, I was so confused @_@, really need help, thank you very much.

**Comment by gyteng** [comment]
when you run `ssmgr -t m`, you have to set plugins,
for example:
with `-c telegram.yml`, it will load config file in `~/.ssmgr/telegram.yml`, you can follow [this](https://github.com/shadowsocks/shadowsocks-manager/blob/master/plugins/telegram/README.md) to manage them with telegram bot.

**Comment by gyteng** [comment]
it's a little complicated, if you run ssmgr first time, the default config files will add to direction `~/.ssmgr`

**Comment by cokebar** [comment]
@shiqwang When webgui is finished, all things can be simpler.
